import { create } from 'zustand';

export type LanguageCode =
  | 'en'
  | 'hi'
  | 'pa'
  | 'bn'
  | 'ta'
  | 'te'
  | 'mr'
  | 'gu'
  | 'kn'
  | 'ml'
  | 'or';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇮🇳' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം', flag: '🇮🇳' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Top Bar & Navigation
    defense_command: 'DEFENSE COMMAND',
    app_title: 'Personnel Stress & Welfare Intelligence Command',
    jai_hind: 'Jai Hind',
    welcome_soldier:
      'Your personal daily wellness cockpit. Track your biological recovery, log daily field telemetry, review AI health recommendations, and access tactical resilience protocols.',
    personal_dashboard: 'Personal Dashboard',
    daily_checkin: 'Daily Check-ins',
    ai_health_insights: 'AI Health Insights',
    recovery_activities: 'Recovery Activities',
    my_alerts_sos: 'My Alerts & SOS',
    my_service_record: 'My Service Record',
    unit_hierarchy: 'Unit Hierarchy Tree',
    sos_distress_alert: 'SOS Distress Alert',
    sos_active: 'SOS Active (Command Alerted)',
    record_daily_checkin: 'Record Daily Check-in',
    form_16_dossier: 'Form 16 Dossier 🖨️',
    self_assessment: 'Self-Assessment',
    assessment_title: 'Confidential Psychological Self-Assessment',

    // Privacy Shield
    article_42a_title: 'Article 42-A Defense Medical Privilege & Statutory Confidentiality Active',
    non_punitive_badge: 'Non-Punitive Safe Harbor',
    article_42a_desc:
      'Your subjective emotional responses, survey choices, and psychological check-ins are legally classified as Privileged Medical Records. Encrypted (AES-256 GCM) and accessible ONLY to certified Medical Officers and Welfare Counselors.',
    view_transparency_matrix: 'View Transparency Matrix',
    hide_privacy_barrier: 'Hide Privacy Barrier',
    what_doctors_see: 'What Certified Medical Officers See:',
    what_commanders_see: 'What Your Unit Commander Sees (Masked):',

    // Check-in Form
    checkin_heading: 'Daily Confidential Wellness Check-in',
    checkin_sub:
      'Record your 24h biological state. Data is analyzed confidentially by AI for burnout prevention.',
    sleep_hours: 'Sleep Hours (Last 24h)',
    mental_mood: 'Mental State / Mood',
    fatigue_level: 'Fatigue Level',
    workload_strain: 'Operational Workload',
    musculoskeletal_strain: 'Musculoskeletal Strain',
    duty_days_without_leave: 'Duty Days Without Leave',
    confidential_notes: 'Confidential Field Observations / Sleep Disturbances (Optional)',
    submit_checkin: 'Submit Daily Check-in',
    syncing: 'Syncing...',
    checkin_success: 'Daily Check-in registered successfully! Telemetry synchronized.',

    // Vitals & Scores
    wellness_score_heading: 'Personal Wellness Score & Vitals',
    combat_fit: 'Combat Fit',
    optimal_status: 'OPTIMAL OPERATIONAL STATUS',
    sleep_restoration: 'Sleep Restoration',
    fatigue_burnout: 'Fatigue & Burnout Index',
    physical_strain: 'Physical Strain',
    consecutive_duty_days: 'Consecutive Operational Days',

    // Box Breathing
    tactical_resilience: 'Tactical Stress Resilience Protocol & Box Breathing',
    box_breathing_desc:
      'Mil-spec 4-4-4-4 autonomic nervous system down-regulation for acute vigilance control.',
    inhale: 'Inhale',
    hold: 'Hold',
    exhale: 'Exhale',
    pause: 'Pause',
    start_protocol: 'Start Breathing Cycle',
    pause_protocol: 'Pause Cycle',
    reset_protocol: 'Reset Protocol',

    // Hierarchy
    corps_level: 'Corps Command',
    division_level: 'Division Command',
    brigade_level: 'Brigade Command',
    battalion_level: 'Battalion Level',
    company_level: 'Company Outpost',
    section_drilldown: 'Chain of Command & Force Structure',

    // Likert Options
    opt_never: 'Never',
    opt_rarely: 'Rarely',
    opt_sometimes: 'Sometimes',
    opt_often: 'Often',
    opt_always: 'Almost Always',
  },

  hi: {
    defense_command: 'रक्षा कमान',
    app_title: 'सैनिक तनाव एवं कल्याण आसूचना कमान प्रणाली',
    jai_hind: 'जय हिंद',
    welcome_soldier:
      'आपका व्यक्तिगत दैनिक कल्याण कॉकपिट। अपनी शारीरिक रिकवरी ट्रैक करें, दैनिक फील्ड टेलीमेट्री दर्ज करें, एआई स्वास्थ्य अनुशंसाएं देखें और सामरिक विश्राम प्रोटोकॉल तक पहुंचें।',
    personal_dashboard: 'व्यक्तिगत डैशबोर्ड',
    daily_checkin: 'दैनिक उपस्थिति व जांच',
    ai_health_insights: 'एआई स्वास्थ्य अंतर्दृष्टि',
    recovery_activities: 'पुनर्प्राप्ति गतिविधियाँ',
    my_alerts_sos: 'मेरी आपातकालीन सूचनाएं (SOS)',
    my_service_record: 'मेरा सेवा रिकॉर्ड',
    unit_hierarchy: 'सैन्य इकाई पदानुक्रम वृक्ष',
    sos_distress_alert: 'आपातकालीन संकट अलार्म (SOS)',
    sos_active: 'आपातकाल सक्रिय (कमान को सूचित किया गया)',
    record_daily_checkin: 'दैनिक चेक-इन दर्ज करें',
    form_16_dossier: 'फॉर्म 16 कल्याण डोजियर 🖨️',
    self_assessment: 'आत्म-मूल्यांकन',
    assessment_title: 'गोपनीय मनोवैज्ञानिक आत्म-मूल्यांकन',

    article_42a_title: 'अनुच्छेद 42-ए रक्षा चिकित्सा विशेषाधिकार एवं वैधानिक गोपनीयता सक्रिय',
    non_punitive_badge: 'दंडात्मक कार्रवाई रहित सुरक्षित क्षेत्र',
    article_42a_desc:
      'आपकी आंतरिक भावनाएं, प्रतिक्रियाएं और मनोवैज्ञानिक चेक-इन कानूनी रूप से विशेषाधिकार प्राप्त मेडिकल रिकॉर्ड हैं। एईएस-256 द्वारा एन्क्रिप्टेड और केवल प्रमाणित सैन्य चिकित्सा अधिकारियों एवं कल्याण परामर्शदाताओं के लिए दृश्यमान।',
    view_transparency_matrix: 'गोपनीयता और पारदर्शिता मैट्रिक्स देखें',
    hide_privacy_barrier: 'गोपनीयता मैट्रिक्स छिपाएं',
    what_doctors_see: 'सैन्य चिकित्सा अधिकारी क्या देख सकते हैं:',
    what_commanders_see: 'कमांडिंग ऑफिसर क्या देखते हैं (केवल समग्र):',

    checkin_heading: 'दैनिक गोपनीय कल्याण चेक-इन',
    checkin_sub:
      'पिछले 24 घंटों की अपनी शारीरिक स्थिति दर्ज करें। यह डेटा बर्नआउट रोकथाम के लिए एआई द्वारा पूरी तरह गोपनीय रखा जाता है।',
    sleep_hours: 'नींद के घंटे (विगत 24 घंटे)',
    mental_mood: 'मानसिक स्थिति / मनोदशा',
    fatigue_level: 'थकान का स्तर',
    workload_strain: 'परिचालन कार्यभार',
    musculoskeletal_strain: 'शारीरिक व मांसपेशियों का तनाव',
    duty_days_without_leave: 'बिना छुट्टी के निरंतर ड्यूटी के दिन',
    confidential_notes: 'गोपनीय फील्ड टिप्पणियां / नींद में व्यवधान (वैकल्पिक)',
    submit_checkin: 'दैनिक चेक-इन जमा करें',
    syncing: 'सिंक्रनाइज़ हो रहा है...',
    checkin_success: 'दैनिक चेक-इन सफलतापूर्वक दर्ज हुआ! टेलीमेट्री डेटा सुरक्षित सिंक्रनाइज़ किया गया।',

    wellness_score_heading: 'व्यक्तिगत कल्याण स्कोर एवं महत्वपूर्ण जीवन संकेत',
    combat_fit: 'युद्ध हेतु पूर्णतः सक्षम',
    optimal_status: 'इष्टतम परिचालन स्थिति',
    sleep_restoration: 'नींद की बहाली',
    fatigue_burnout: 'थकान एवं बर्नआउट सूचकांक',
    physical_strain: 'शारीरिक भार',
    consecutive_duty_days: 'लगातार ड्यूटी के दिन',

    tactical_resilience: 'सामरिक तनाव लचीलापन प्रोटोकॉल (बॉक्स श्वास व्यायाम)',
    box_breathing_desc:
      'तीव्र सतर्कता और मानसिक तनाव नियमन हेतु 4-4-4-4 सेकंड का सैन्य श्वास नियमन।',
    inhale: 'श्वास भीतर लें',
    hold: 'रोक कर रखें',
    exhale: 'श्वास बाहर छोड़ें',
    pause: 'विश्राम दें',
    start_protocol: 'श्वास चक्र प्रारंभ करें',
    pause_protocol: 'चक्र रोकें',
    reset_protocol: 'प्रोटोकॉल रीसेट करें',

    corps_level: 'कोर कमान मुख्यालय',
    division_level: 'डिवीज़न कमान',
    brigade_level: 'ब्रिगेड मुख्यालय',
    battalion_level: 'बटालियन स्तर',
    company_level: 'कंपनी फॉरवर्ड पोस्ट',
    section_drilldown: 'सैन्य कमान श्रृंखला एवं बल संरचना',

    opt_never: 'कभी नहीं',
    opt_rarely: 'शायद ही कभी',
    opt_sometimes: 'कभी-कभी',
    opt_often: 'अक्सर',
    opt_always: 'लगभग हमेशा',
  },

  pa: {
    defense_command: 'ਰੱਖਿਆ ਕਮਾਂਡ',
    app_title: 'ਜਵਾਨ ਤਣਾਅ ਅਤੇ ਭਲਾਈ ਇੰਟੈਲੀਜੈਂਸ ਕਮਾਂਡ ਸਿਸਟਮ',
    jai_hind: 'ਜੈ ਹਿੰਦ',
    welcome_soldier:
      'ਤੁਹਾਡਾ ਨਿੱਜੀ ਰੋਜ਼ਾਨਾ ਭਲਾਈ ਕਾਕਪਿਟ। ਆਪਣੀ ਸਰੀਰਕ ਰਿਕਵਰੀ ਨੂੰ ਟਰੈਕ ਕਰੋ, ਰੋਜ਼ਾਨਾ ਫੀਲਡ ਟੈਲੀਮੈਟਰੀ ਦਰਜ ਕਰੋ ਅਤੇ ਤਣਾਅ-ਮੁਕਤੀ ਪ੍ਰੋਟੋਕੋਲ ਪ੍ਰਾਪਤ ਕਰੋ।',
    personal_dashboard: 'ਨਿੱਜੀ ਡੈਸ਼ਬੋਰਡ',
    daily_checkin: 'ਰੋਜ਼ਾਨਾ ਚੈੱਕ-ਇਨ',
    ai_health_insights: 'ਏਆਈ ਸਿਹਤ ਸੂਝ',
    recovery_activities: 'ਰਿਕਵਰੀ ਗਤੀਵਿਧੀਆਂ',
    my_alerts_sos: 'ਮੇਰੇ ਐਮਰਜੈਂਸੀ ਅਲਰਟ (SOS)',
    my_service_record: 'ਮੇਰਾ ਸੇਵਾ ਰਿਕਾਰਡ',
    unit_hierarchy: 'ਯੂਨਿਟ ਲੜੀਵਾਰ ਢਾਂਚਾ ਰੁੱਖ',
    sos_distress_alert: 'ਸੰਕਟਕਾਲੀਨ ਐਮਰਜੈਂਸੀ ਅਲਰਟ (SOS)',
    sos_active: 'ਐਮਰਜੈਂਸੀ ਚਾਲੂ (ਕਮਾਂਡ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ)',
    record_daily_checkin: 'ਰੋਜ਼ਾਨਾ ਚੈੱਕ-ਇਨ ਦਰਜ ਕਰੋ',
    form_16_dossier: 'ਫਾਰਮ 16 ਭਲਾਈ ਡੋਜ਼ੀਅਰ 🖨️',
    self_assessment: 'ਸਵੈ-ਮੁਲਾਂਕਣ',
    assessment_title: 'ਗੁਪਤ ਮਨੋਵਿਗਿਆਨਕ ਸਵੈ-ਮੁਲਾਂਕਣ',

    article_42a_title: 'ਆਰਟੀਕਲ 42-ਏ ਰੱਖਿਆ ਮੈਡੀਕਲ ਵਿਸ਼ੇਸ਼-ਅਧਿਕਾਰ ਅਤੇ ਕਾਨੂੰਨੀ ਗੁਪਤਤਾ ਸਰਗਰਮ',
    non_punitive_badge: 'ਦੰਡ ਰਹਿਤ ਸੁਰੱਖਿਅਤ ਖੇਤਰ',
    article_42a_desc:
      'ਤੁਹਾਡੀਆਂ ਨਿੱਜੀ ਭਾਵਨਾਵਾਂ ਅਤੇ ਮਨੋਵਿਗਿਆਨਕ ਜਵਾਬ ਪੂਰੀ ਤਰ੍ਹਾਂ ਗੁਪਤ ਹਨ। ਏਈਐਸ-256 ਦੁਆਰਾ ਇਨਕ੍ਰਿਪਟਡ ਅਤੇ ਕੇਵਲ ਯੂਨਿਟ ਡਾਕਟਰਾਂ ਲਈ ਪਹੁੰਚਯੋਗ ਹਨ।',
    view_transparency_matrix: 'ਗੁਪਤਤਾ ਮੈਟ੍ਰਿਕਸ ਵੇਖੋ',
    hide_privacy_barrier: 'ਗੁਪਤਤਾ ਮੈਟ੍ਰਿਕਸ ਛੁਪਾਓ',
    what_doctors_see: 'ਮੈਡੀਕਲ ਅਧਿਕਾਰੀ ਕੀ ਵੇਖਦੇ ਹਨ:',
    what_commanders_see: 'ਕਮਾਂਡਿੰਗ ਅਫਸਰ ਕੀ ਵੇਖਦੇ ਹਨ (ਸਿਰਫ ਕੁੱਲ ਤਿਆਰੀ):',

    checkin_heading: 'ਰੋਜ਼ਾਨਾ ਗੁਪਤ ਵੈਲਨੈੱਸ ਚੈੱਕ-ਇਨ',
    checkin_sub: 'ਪਿਛਲੇ 24 ਘੰਟਿਆਂ ਦੀ ਆਪਣੀ ਸਰੀਰਕ ਸਥਿਤੀ ਦਰਜ ਕਰੋ।',
    sleep_hours: 'ਨੀਂਦ ਦੇ ਘੰਟੇ (ਪਿਛਲੇ 24 ਘੰਟੇ)',
    mental_mood: 'ਮਾਨਸਿਕ ਸਥਿਤੀ / ਮੂਡ',
    fatigue_level: 'ਥਕਾਵਟ ਦਾ ਪੱਧਰ',
    workload_strain: 'ਡਿਊਟੀ ਦਾ ਕੰਮਕਾਜੀ ਦਬਾਅ',
    musculoskeletal_strain: 'ਸਰੀਰਕ ਖਿੱਚ / ਦਰਦ',
    duty_days_without_leave: 'ਬਿਨਾਂ ਛੁੱਟੀ ਦੇ ਲਗਾਤਾਰ ਦਿਨ',
    confidential_notes: 'ਗੁਪਤ ਫੀਲਡ ਟਿੱਪਣੀਆਂ (ਵਿਕਲਪਿਕ)',
    submit_checkin: 'ਦੈਨਿਕ ਚੈੱਕ-ਇਨ ਜਮ੍ਹਾਂ ਕਰੋ',
    syncing: 'ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...',
    checkin_success: 'ਰੋਜ਼ਾਨਾ ਚੈੱਕ-ਇਨ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਹੋ ਗਿਆ!',

    wellness_score_heading: 'ਨਿੱਜੀ ਵੈਲਨੈੱਸ ਸਕੋਰ ਅਤੇ ਜ਼ਰੂਰੀ ਸੰਕੇਤ',
    combat_fit: 'ਮਿਸ਼ਨ ਲਈ ਫਿੱਟ',
    optimal_status: 'ਸਭ ਤੋਂ ਉੱਤਮ ਸਥਿਤੀ',
    sleep_restoration: 'ਨੀਂਦ ਦੀ ਬਹਾਲੀ',
    fatigue_burnout: 'ਥਕਾਵਟ ਸੂਚਕਾਂਕ',
    physical_strain: 'ਸਰੀਰਕ ਤਣਾਅ',
    consecutive_duty_days: 'ਲਗਾਤਾਰ ਡਿਊਟੀ ਦੇ ਦਿਨ',

    tactical_resilience: 'ਸੈਨਿਕ ਬਾਕਸ ਸਾਹ ਪ੍ਰੋਟੋਕੋਲ',
    box_breathing_desc: '4-4-4-4 ਸਕਿੰਟ ਦਾ ਤਣਾਅ ਨਿਯੰਤਰਣ ਸਾਹ ਅਭਿਆਸ।',
    inhale: 'ਸਾਹ ਅੰਦਰ ਖਿੱਚੋ',
    hold: 'ਰੋਕ ਕੇ ਰੱਖੋ',
    exhale: 'ਸਾਹ ਬਾਹਰ ਛੱਡੋ',
    pause: 'ਵਿਰਾਮ ਲਵੋ',
    start_protocol: 'ਚੱਕਰ ਸ਼ੁਰੂ ਕਰੋ',
    pause_protocol: 'ਰੋਕੋ',
    reset_protocol: 'ਦੁਬਾਰਾ ਸੈੱਟ ਕਰੋ',

    corps_level: 'ਕੋਰ ਕਮਾਂਡ',
    division_level: 'ਡਿਵੀਜ਼ਨ ਕਮਾਂਡ',
    brigade_level: 'ਬ੍ਰਿਗੇਡ ਕਮਾਂਡ',
    battalion_level: 'ਬਟਾਲੀਅਨ ਪੱਧਰ',
    company_level: 'ਕੰਪਨੀ ਪੋਸਟ',
    section_drilldown: 'ਫੌਜੀ ਲੜੀਵਾਰ ਢਾਂਚਾ',

    opt_never: 'ਕਦੇ ਨਹੀਂ',
    opt_rarely: 'ਬਹੁਤ ਘੱਟ',
    opt_sometimes: 'ਕਦੇ-ਕਦੇ',
    opt_often: 'ਅਕਸਰ',
    opt_always: 'ਲਗਭਗ ਹਮੇਸ਼ਾ',
  },

  bn: {
    defense_command: 'প্রতিরক্ষা কমান্ড',
    app_title: 'সেনা মানসিক চাপ ও কল্যাণ বুদ্ধিমত্তা কমান্ড সিস্টেম',
    jai_hind: 'জয় হিন্দ',
    welcome_soldier:
      'আপনার ব্যক্তিগত দৈনিক সুস্থতা ককপিট। আপনার শারীরিক পুনরুদ্ধার পর্যবেক্ষণ করুন এবং এআই স্বাস্থ্য নির্দেশিকা পান।',
    personal_dashboard: 'ব্যক্তিগত ড্যাশবোর্ড',
    daily_checkin: 'দৈনিক চেক-ইন',
    ai_health_insights: 'এআই স্বাস্থ্য অন্তর্দৃষ্টি',
    recovery_activities: 'পুনরুদ্ধার কার্যক্রম',
    my_alerts_sos: 'জরুরী সতর্কতা (SOS)',
    my_service_record: 'আমার পরিষেবা রেকর্ড',
    unit_hierarchy: 'সামরিক পদক্রম কাঠামো বৃক্ষ',
    sos_distress_alert: 'জরুরী এসওএস বিপদ সংকেত',
    sos_active: 'এসওএস সক্রিয় (কমান্ডকে সতর্ক করা হয়েছে)',
    record_daily_checkin: 'দৈনিক চেক-ইন নথিভুক্ত করুন',
    form_16_dossier: 'ফর্ম ১৬ কল্যাণ ডসিয়ার 🖨️',
    self_assessment: 'আত্ম-মূল্যায়ন',
    assessment_title: 'গোপনীয় মনস্তাত্ত্বিক আত্ম-মূল্যায়ন',

    article_42a_title: 'অনুচ্ছেদ ৪২-এ প্রতিরক্ষা চিকিৎসা অধিকার ও সংবিধিবদ্ধ গোপনীয়তা সক্রিয়',
    non_punitive_badge: 'শাস্তিমূলক ব্যবস্থা মুক্ত নিরাপদ আশ্রয়',
    article_42a_desc:
      'আপনার মানসিক অনুভূতি এবং স্বাস্থ্য চেক-ইন সম্পূর্ণ গোপনীয় এবং আইনি সুরক্ষিত চিকিৎসা রেকর্ড। এটি কেবল চিকিৎসকদের জন্য দৃশ্যমান।',
    view_transparency_matrix: 'স্বচ্ছতা ম্যাট্রিক্স দেখুন',
    hide_privacy_barrier: 'গোপনীয়তা ম্যাট্রিক্স লুকান',
    what_doctors_see: 'চিকিৎসা কর্মকর্তারা যা দেখতে পারেন:',
    what_commanders_see: 'কমান্ডিং অফিসার যা দেখেন (কেবল সার্বিক প্রস্তুতি):',

    checkin_heading: 'দৈনিক গোপনীয় স্বাস্থ্য চেক-ইন',
    checkin_sub: 'গত ২৪ ঘণ্টার শারীরিক অবস্থা নথিভুক্ত করুন।',
    sleep_hours: 'ঘুমের সময়কাল (বিগত ২৪ ঘণ্টা)',
    mental_mood: 'মানসিক অবস্থা / মেজাজ',
    fatigue_level: 'ক্লান্তির মাত্রা',
    workload_strain: 'অপারেশনাল কাজের চাপ',
    musculoskeletal_strain: 'শারীরিক পেশীর চাপ',
    duty_days_without_leave: 'ছুটি ছাড়া একটানা দায়িত্ব পালনের দিন',
    confidential_notes: 'গোপনীয় ফিল্ড পর্যবেক্ষণ (ঐচ্ছিক)',
    submit_checkin: 'দৈনিক চেক-ইন জমা দিন',
    syncing: 'সিঙ্ক হচ্ছে...',
    checkin_success: 'দৈনিক চেক-ইন সফলভাবে জমা হয়েছে!',

    wellness_score_heading: 'ব্যক্তিগত সুস্থতা স্কোর ও গুরুত্বপূর্ণ সূচক',
    combat_fit: 'মিশনের জন্য সম্পূর্ণ প্রস্তুত',
    optimal_status: 'সর্বোত্তম অপারেশনাল অবস্থা',
    sleep_restoration: 'ঘুমের পুনরুদ্ধার',
    fatigue_burnout: 'ক্লান্তি সূচক',
    physical_strain: 'শারীরিক ক্লান্তি',
    consecutive_duty_days: 'টানা দায়িত্বের দিন',

    tactical_resilience: 'ট্যাকটিক্যাল বক্স শ্বাস-প্রশ্বাস প্রোটোকল',
    box_breathing_desc: 'মানসিক চাপ নিয়ন্ত্রণে ৪-৪-৪-৪ সেকেন্ডের সামরিক শ্বাস-প্রশ্বাস পদ্ধতি।',
    inhale: 'শ্বাস গ্রহণ করুন',
    hold: 'ধরে রাখুন',
    exhale: 'শ্বাস ছাড়ুন',
    pause: 'বিরতি দিন',
    start_protocol: 'চক্র শুরু করুন',
    pause_protocol: 'চক্র থামান',
    reset_protocol: 'রিসেট করুন',

    corps_level: 'কোর কমান্ড',
    division_level: 'ডিভিশন কমান্ড',
    brigade_level: 'ব্রিগেড কমান্ড',
    battalion_level: 'ব্যাটালিয়ন স্তর',
    company_level: 'কোম্পানি পোস্ট',
    section_drilldown: 'সামরিক কমাণ্ড কাঠামো',

    opt_never: 'কখনও না',
    opt_rarely: 'কদাচিৎ',
    opt_sometimes: 'মাঝে মাঝে',
    opt_often: 'প্রায়ই',
    opt_always: 'সবসময় প্রায়',
  },

  ta: {
    defense_command: 'பாதுகாப்புக் கட்டளை',
    app_title: 'வீரர் மன அழுத்த மற்றும் நலன் புலனாய்வு கட்டளை அமைப்பு',
    jai_hind: 'ஜெய் ஹிந்த்',
    welcome_soldier:
      'உங்கள் தனிப்பட்ட தினசரி நல்வாழ்வு கட்டுப்பாட்டு மையம். உங்கள் உடல்நிலை மீட்டெடுப்பைக் கண்காணித்து, ஏஐ சுகாதாரப் பரிந்துரைகளைப் பெறுங்கள்.',
    personal_dashboard: 'தனிப்பட்ட டாஷ்போர்டு',
    daily_checkin: 'தினசரி பதிவு',
    ai_health_insights: 'ஏஐ சுகாதார நுண்ணறிவு',
    recovery_activities: 'மீட்பு நடவடிக்கைகள்',
    my_alerts_sos: 'எனது அவசர எச்சரிக்கைகள் (SOS)',
    my_service_record: 'எனது சேவைப் பதிவு',
    unit_hierarchy: 'படைப் பிரிவு படிநிலை மரம்',
    sos_distress_alert: 'அவசர ஆபத்து எச்சரிக்கை (SOS)',
    sos_active: 'அவசர எச்சரிக்கை செயலில் உள்ளது',
    record_daily_checkin: 'தினசரி பதிவைச் சேர்க்கவும்',
    form_16_dossier: 'படிவம் 16 நலன் ஆவணம் 🖨️',
    self_assessment: 'சுய மதிப்பீடு',
    assessment_title: 'ரகசிய உளவியல் சுய மதிப்பீடு',

    article_42a_title: 'பிரிவு 42-ஏ பாதுகாப்பு மருத்துவச் சிறப்புரிமை & சட்டரீதியான ரகசியத்தன்மை செயலில் உள்ளது',
    non_punitive_badge: 'தண்டனையற்ற பாதுகாப்பு புகலிடம்',
    article_42a_desc:
      'உங்கள் தனிப்பட்ட மனநிலை மற்றும் மருத்துவப் பதிவுகள் சட்டப்பூர்வமாகப் பாதுகாக்கப்பட்டவை. இராணுவ மருத்துவர்களுக்கு மட்டுமே அணுகல் உண்டு.',
    view_transparency_matrix: 'வெளிப்படைத்தன்மை மேட்ரிக்ஸைப் பார்க்கவும்',
    hide_privacy_barrier: 'மேட்ரிக்ஸை மறைக்கவும்',
    what_doctors_see: 'மருத்துவ அதிகாரிகள் பார்ப்பது:',
    what_commanders_see: 'படைத் தளபதி பார்ப்பது (மொத்தத் தயார்நிலை மட்டுமே):',

    checkin_heading: 'தினசரி ரகசிய நல்வாழ்வு பதிவு',
    checkin_sub: 'கடந்த 24 மணி நேர உடல் நிலையைப் பதிவு செய்யவும்.',
    sleep_hours: 'தூங்கிய மணிநேரம் (கடந்த 24 மணி)',
    mental_mood: 'மனநிலை / உணர்வு நிலை',
    fatigue_level: 'சோர்வு நிலை',
    workload_strain: 'பணிப்பளு அழுத்தம்',
    musculoskeletal_strain: 'உடல் தசை வலி',
    duty_days_without_leave: 'விடுமுறை இல்லாத தொடர் பணி நாட்கள்',
    confidential_notes: 'ரகசியக் குறிப்புகள் (விருப்பத்தேர்வு)',
    submit_checkin: 'பதிவைச் சமர்ப்பிக்கவும்',
    syncing: 'ஒத்திசைக்கப்படுகிறது...',
    checkin_success: 'தினசரி பதிவு வெற்றிகரமாகச் சமர்ப்பிக்கப்பட்டது!',

    wellness_score_heading: 'தனிப்பட்ட நல்வாழ்வு மதிப்பீடு மற்றும் முக்கிய அறிகுறிகள்',
    combat_fit: 'போருக்குத் தயார்',
    optimal_status: 'உகந்த செயல்பாட்டு நிலை',
    sleep_restoration: 'தூக்க மீட்பு',
    fatigue_burnout: 'சோர்வுக் குறியீடு',
    physical_strain: 'உடல் சிரமம்',
    consecutive_duty_days: 'தொடர் பணி நாட்கள்',

    tactical_resilience: 'தந்திரோபாய பாக்ஸ் சுவாசப் பயிற்சி',
    box_breathing_desc: 'மன அழுத்தத்தைக் குறைக்க 4-4-4-4 வினாடி இராணுவ மூச்சுப் பயிற்சி.',
    inhale: 'மூச்சை உள்ளே இழுக்கவும்',
    hold: 'மூச்சை அடக்கவும்',
    exhale: 'மூச்சை வெளியே விடவும்',
    pause: 'சிறிது இடைவெளி விடவும்',
    start_protocol: 'சுழற்சியைத் தொடங்கவும்',
    pause_protocol: 'நிறுத்தவும்',
    reset_protocol: 'மீட்டமைக்கவும்',

    corps_level: 'கோர் கட்டளைப் பிரிவு',
    division_level: 'டிவிஷன் கட்டளைப் பிரிவு',
    brigade_level: 'பிரிகேட் கட்டளைப் பிரிவு',
    battalion_level: 'பட்டாலியன் நிலை',
    company_level: 'கம்பெனி புறக்காவல் நிலை',
    section_drilldown: 'படைப் படிநிலை கட்டமைப்பு',

    opt_never: 'ஒருபோதும் இல்லை',
    opt_rarely: 'அரிதாக',
    opt_sometimes: 'சில நேரங்களில்',
    opt_often: 'அடிக்கடி',
    opt_always: 'கிட்டத்தட்ட எப்போதும்',
  },

  te: {
    defense_command: 'రక్షణ కమాండ్',
    app_title: 'సైనిక ఒత్తిడి & సంక్షేమ ఇంటెలిజెన్స్ కమాండ్ సిస్టమ్',
    jai_hind: 'జై హింద్',
    welcome_soldier:
      'మీ వ్యక్తిగత రోజువారీ వెల్‌నెస్ కాక్‌పిట్. మీ శారీరక పునరుద్ధరణను పర్యవేక్షించండి మరియు ఏఐ ఆరోగ్య సూచనలను పొందండి.',
    personal_dashboard: 'వ్యక్తిగత డాష్‌బోర్డ్',
    daily_checkin: 'రోజువారీ చెకిన్',
    ai_health_insights: 'ఏఐ ఆరోగ్య విశ్లేషణ',
    recovery_activities: 'విశ్రాంతి ప్రక్రియలు',
    my_alerts_sos: 'అత్యవసర హెచ్చరికలు (SOS)',
    my_service_record: 'నా సేవా రికార్డు',
    unit_hierarchy: 'యూనిట్ శ్రేణి నిర్మాణం',
    sos_distress_alert: 'అత్యవసర ఆపద హెచ్చరిక (SOS)',
    sos_active: 'అత్యవసర హెచ్చరిక చురుకుగా ఉంది',
    record_daily_checkin: 'రోజువారీ చెకిన్ నమోదు చేయండి',
    form_16_dossier: 'ఫారం 16 సంక్షేమ నివేదిక 🖨️',
    self_assessment: 'స్వీయ మూల్యాంకనం',
    assessment_title: 'రహస్య మానసిక స్వీయ మూల్యాంకనం',

    article_42a_title: 'ఆర్టికల్ 42-ఎ రక్షణ వైద్య విశేష రక్షణ చట్టబద్ధమైన గోప్యత చురుకుగా ఉంది',
    non_punitive_badge: 'శిక్షారహిత సురక్షిత ప్రాంతం',
    article_42a_desc:
      'మీ మానసిక భావాలు మరియు సర్వే స్పందనలు పూర్తిగా చట్టబద్ధమైన వైద్య రికార్డులుగా రక్షించబడ్డాయి.',
    view_transparency_matrix: 'పారదర్శకత మాత్రికను చూడండి',
    hide_privacy_barrier: 'గోప్యతా మాత్రికను దాచండి',
    what_doctors_see: 'వైద్యాధికారులు ఏమి చూడగలరు:',
    what_commanders_see: 'కమాండింగ్ అధికారులు ఏమి చూడగలరు (సమిష్టి మాత్రమే):',

    checkin_heading: 'రోజువారీ రహస్య వెల్‌నెస్ చెకిన్',
    checkin_sub: 'గత 24 గంటల మీ శారీరక స్థితిని నమోదు చేయండి.',
    sleep_hours: 'నిద్ర గంటలు (గత 24 గంటలు)',
    mental_mood: 'మానసిక స్థితి / మూడ్',
    fatigue_level: 'అలసట స్థాయి',
    workload_strain: 'కార్యాచరణ పనిభారం',
    musculoskeletal_strain: 'శారీరక కండరాల ఒత్తిడి',
    duty_days_without_leave: 'సెలవు లేకుండా నిరంతర విధి రోజులు',
    confidential_notes: 'రహస్య పరిశీలనలు (ఐచ్ఛికం)',
    submit_checkin: 'చెకిన్ సమర్పించండి',
    syncing: 'సింక్ అవుతోంది...',
    checkin_success: 'రోజువారీ చెకిన్ విజయవంతంగా నమోదైంది!',

    wellness_score_heading: 'వ్యక్తిగత వెల్‌నెస్ స్కోరు & జీవ సంకేతాలు',
    combat_fit: 'యుద్ధానికి సిద్ధం',
    optimal_status: 'ఉత్తమ కార్యాచరణ స్థితి',
    sleep_restoration: 'నిద్ర పునరుద్ధరణ',
    fatigue_burnout: 'అలసట & బర్న్‌అవుట్ సూచిక',
    physical_strain: 'శారీరక శ్రమ',
    consecutive_duty_days: 'నిరంతర విధి రోజులు',

    tactical_resilience: 'టాక్టికల్ బాక్స్ శ్వాస నియంత్రణ',
    box_breathing_desc: 'తీవ్ర ఒత్తిడి నియంత్రణ కోసం 4-4-4-4 సైనిక శ్వాస విధానం.',
    inhale: 'శ్వాస పీల్చండి',
    hold: 'బిగబట్టండి',
    exhale: 'శ్వాస వదలండి',
    pause: 'విరామం',
    start_protocol: 'ప్రారంభించండి',
    pause_protocol: 'ఆపండి',
    reset_protocol: 'రీసెట్ చేయండి',

    corps_level: 'కోర్ కమాండ్',
    division_level: 'డివిజన్ కమాండ్',
    brigade_level: 'బ్రిగేడ్ కమాండ్',
    battalion_level: 'బెటాలియన్ స్థాయి',
    company_level: 'కంపెనీ అవుట్‌పోస్ట్',
    section_drilldown: 'కమాండ్ శ్రేణి మరియు బలగాల నిర్మాణం',

    opt_never: 'ఎప్పుడూ లేదు',
    opt_rarely: 'అరుదుగా',
    opt_sometimes: 'కొన్నిసార్లు',
    opt_often: 'తరచుగా',
    opt_always: 'దాదాపు ఎల్లప్పుడూ',
  },

  mr: {
    defense_command: 'संरक्षण कमांड',
    app_title: 'सैनिक तणाव व कल्याण गुप्तचर कमांड प्रणाली',
    jai_hind: 'जय हिंद',
    welcome_soldier:
      'तुमचा वैयक्तिक दैनिक कल्याण कॉकपिट. शारीरिक सुधारणा ट्रॅक करा आणि एआय आरोग्य सल्ले मिळवा.',
    personal_dashboard: 'वैयक्तिक डॅशबोर्ड',
    daily_checkin: 'दैनिक चेक-इन',
    ai_health_insights: 'एआय आरोग्य माहिती',
    recovery_activities: 'पुनर्प्राप्ती उपक्रम',
    my_alerts_sos: 'आपत्कालीन इशारे (SOS)',
    my_service_record: 'माझा सेवा अभिलेख',
    unit_hierarchy: 'लष्करी घटक पदानुक्रम रचना',
    sos_distress_alert: 'आपत्कालीन संकटाची सूचना (SOS)',
    sos_active: 'आपत्कालीन सक्रिय (कमांडला सूचित केले)',
    record_daily_checkin: 'दैनिक चेक-इन नोंदवा',
    form_16_dossier: 'फॉर्म १६ कल्याण डॉसियर 🖨️',
    self_assessment: 'स्व-मूल्यांकन',
    assessment_title: 'गोपनीय मानसशास्त्रीय स्व-मूल्यांकन',

    article_42a_title: 'अनुच्छेद ४२-ए संरक्षण वैद्यकीय विशेषाधिकार आणि कायदेशीर गोपनीयता सक्रिय',
    non_punitive_badge: 'शिक्षारहित सुरक्षित क्षेत्र',
    article_42a_desc:
      'तुमच्या वैयक्तिक भावना आणि मानसिक माहिती पूर्णपणे संरक्षित व गोपनीय आहे.',
    view_transparency_matrix: 'पारदर्शकता मॅट्रिक्स पहा',
    hide_privacy_barrier: 'मॅट्रिक्स लपवा',
    what_doctors_see: 'वैद्यकीय अधिकारी काय पाहू शकतात:',
    what_commanders_see: 'कमांडिंग ऑफिसर काय पाहतात (केवळ एकूण):',

    checkin_heading: 'दैनिक गोपनीय कल्याण चेक-इन',
    checkin_sub: 'गेल्या २४ तासांतील शारीरिक स्थिती नोंदवा.',
    sleep_hours: 'झोपेचे तास (गेले २४ तास)',
    mental_mood: 'मानसिक स्थिती / मनःस्थिती',
    fatigue_level: 'थकव्याची पातळी',
    workload_strain: 'कामाचा ताण',
    musculoskeletal_strain: 'स्नायूंचा ताण',
    duty_days_without_leave: 'सुट्टीशिवाय सलग ड्युटीचे दिवस',
    confidential_notes: 'गोपनीय नोंदी (पर्यायी)',
    submit_checkin: 'चेक-इन सादर करा',
    syncing: 'सिंक होत आहे...',
    checkin_success: 'दैनिक चेक-इन यशस्वीरित्या नोंदवले गेले!',

    wellness_score_heading: 'वैयक्तिक आरोग्य स्कोअर आणि महत्त्वपूर्ण निर्देशक',
    combat_fit: 'मोहिमेसाठी सज्ज',
    optimal_status: 'उत्कृष्ट परिचालन स्थिती',
    sleep_restoration: 'झोपेची पुनर्प्राप्ती',
    fatigue_burnout: 'थकवा आणि बर्नआउट निर्देशांक',
    physical_strain: 'शारीरिक श्रम',
    consecutive_duty_days: 'सलग ड्युटीचे दिवस',

    tactical_resilience: 'सामरिक बॉक्स श्वासोच्छ्वास व्यायाम',
    box_breathing_desc: 'तणाव नियंत्रणासाठी ४-४-४-४ सेकंदांचा लष्करी श्वास व्यायाम.',
    inhale: 'श्वास आत घ्या',
    hold: 'श्वास रोखा',
    exhale: 'श्वास सोडा',
    pause: 'विश्रांती घ्या',
    start_protocol: 'सुरू करा',
    pause_protocol: 'थांबवा',
    reset_protocol: 'रीसेट करा',

    corps_level: 'कोर कमांड',
    division_level: 'डिव्हिजन कमांड',
    brigade_level: 'ब्रिगेड कमांड',
    battalion_level: 'बटालियन पातळी',
    company_level: 'कंपनी चौकी',
    section_drilldown: 'कमांड साखळी व बल रचना',

    opt_never: 'कधीच नाही',
    opt_rarely: 'क्वचितच',
    opt_sometimes: 'कधीकधी',
    opt_often: 'वारंवार',
    opt_always: 'जवळजवळ नेहमी',
  },

  gu: {
    defense_command: 'સંરક્ષણ કમાન્ડ',
    app_title: 'સૈનિક તણાવ અને કલ્યાણ ઇન્ટેલિજન્સ કમાન્ડ સિસ્ટમ',
    jai_hind: 'જય હિન્દ',
    welcome_soldier:
      'તમારું વ્યક્તિગત દૈનિક વેલનેસ કોકપિટ. શારીરિક સુધારો ટ્રેક કરો અને એઆઈ આરોગ્ય ભલામણો મેળવો.',
    personal_dashboard: 'વ્યક્તિગત ડેશબોર્ડ',
    daily_checkin: 'દૈનિક ચેક-ઇન',
    ai_health_insights: 'એઆઈ આરોગ્ય આંતરદૃષ્ટિ',
    recovery_activities: 'પુનઃપ્રાપ્તિ પ્રવૃત્તિઓ',
    my_alerts_sos: 'મારી કટોકટી ચેતવણીઓ (SOS)',
    my_service_record: 'મારો સેવા રેકોર્ડ',
    unit_hierarchy: 'લશ્કરી એકમ શ્રેણી વૃક્ષ',
    sos_distress_alert: 'કટોકટી ચેતવણી (SOS)',
    sos_active: 'કટોકટી સક્રિય (કમાન્ડને જાણ કરી)',
    record_daily_checkin: 'દૈનિક ચેક-ઇન નોંધો',
    form_16_dossier: 'ફોર્મ 16 કલ્યાણ ડોઝિયર 🖨️',
    self_assessment: 'સ્વ-મૂલ્યાંકન',
    assessment_title: 'ગુપ્ત મનોવૈજ્ઞાનિક સ્વ-મૂલ્યાંકન',

    article_42a_title: 'અનુચ્છેદ 42-એ સંરક્ષણ તબીબી વિશેષાધિકાર અને કાનૂની ગોપનીયતા સક્રિય',
    non_punitive_badge: 'દંડમુક્ત સુરક્ષિત આશ્રય',
    article_42a_desc: 'તમારા વ્યક્તિગત જવાબો સંપૂર્ણપણે સુરક્ષિત તબીબી રેકોર્ડ છે.',
    view_transparency_matrix: 'પારદર્શિતા મેટ્રિક્સ જુઓ',
    hide_privacy_barrier: 'મેટ્રિક્સ છુપાવો',
    what_doctors_see: 'તબીબી અધિકારીઓ શું જોઈ શકે છે:',
    what_commanders_see: 'કમાન્ડિંગ ઓફિસર શું જુએ છે:',

    checkin_heading: 'દૈનિક ગુપ્ત વેલનેસ ચેક-ઇન',
    checkin_sub: 'છેલ્લા 24 કલાકની શારીરિક સ્થિતિ નોંધો.',
    sleep_hours: 'ઊંઘના કલાકો (છેલ્લા 24 કલાક)',
    mental_mood: 'માનસિક સ્થિતિ / મૂડ',
    fatigue_level: 'થાકનું સ્તર',
    workload_strain: 'કામગીરીનો બોજ',
    musculoskeletal_strain: 'સ્નાયુઓનો ખેંચાણ',
    duty_days_without_leave: 'રજા વિના સતત ફરજના દિવસો',
    confidential_notes: 'ગુપ્ત અવલોકનો (વૈકલ્પિક)',
    submit_checkin: 'ચેક-ઇન સબમિટ કરો',
    syncing: 'સિંક થઈ રહ્યું છે...',
    checkin_success: 'દૈનિક ચેક-ઇન સફળતાપૂર્વક નોંધાયું!',

    wellness_score_heading: 'વ્યક્તિગત વેલનેસ સ્કોર અને મહત્વપૂર્ણ સંકેતો',
    combat_fit: 'લડાઇ માટે સક્ષમ',
    optimal_status: 'શ્રેષ્ઠ ઓપરેશનલ સ્થિતિ',
    sleep_restoration: 'ઊંઘની પુનઃપ્રાપ્તિ',
    fatigue_burnout: 'થાક અને બર્નઆઉટ ઇન્ડેક્સ',
    physical_strain: 'શારીરિક શ્રમ',
    consecutive_duty_days: 'સતત ફરજના દિવસો',

    tactical_resilience: 'સૈન્ય બોક્સ શ્વાસ નિયમન',
    box_breathing_desc: '4-4-4-4 સેકન્ડનો લશ્કરી શ્વાસ વ્યાયામ.',
    inhale: 'શ્વાસ અંદર લો',
    hold: 'શ્વાસ રોકો',
    exhale: 'શ્વાસ બહાર કાઢો',
    pause: 'વિરામ આપો',
    start_protocol: 'શરૂ કરો',
    pause_protocol: 'રોકો',
    reset_protocol: 'રીસેટ કરો',

    corps_level: 'કોર કમાન્ડ',
    division_level: 'ડિવિઝન કમાન્ડ',
    brigade_level: 'બ્રિગેડ કમાન્ડ',
    battalion_level: 'બટાલિયન સ્તર',
    company_level: 'કંપની આઉટપોસ્ટ',
    section_drilldown: 'કમાન્ડ સાંકળ અને સૈન્ય રચના',

    opt_never: 'ક્યારેય નહીં',
    opt_rarely: 'ભાગ્યે જ',
    opt_sometimes: 'ક્યારેક',
    opt_often: 'વારંવાર',
    opt_always: 'લગભગ હંમેશા',
  },

  kn: {
    defense_command: 'ರಕ್ಷಣಾ ಕಮಾಂಡ್',
    app_title: 'ಸೈನಿಕ ಒತ್ತಡ ಮತ್ತು ಕಲ್ಯಾಣ ಇಂಟೆಲಿಜೆನ್ಸ್ ಕಮಾಂಡ್ ವ್ಯವಸ್ಥೆ',
    jai_hind: 'ಜೈ ಹಿಂದ್',
    welcome_soldier:
      'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ದೈನಂದಿನ ಕ್ಷೇಮ ಕಾಕ್‌ಪಿಟ್. ದೈಹಿಕ ಚೇತರಿಕೆಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಎಐ ಆರೋಗ್ಯ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
    personal_dashboard: 'ವೈಯಕ್ತಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    daily_checkin: 'ದೈನಂದಿನ ಚೆಕ್-ಇನ್',
    ai_health_insights: 'ಎಐ ಆರೋಗ್ಯ ಒಳನೋಟಗಳು',
    recovery_activities: 'ಚೇತರಿಕೆ ಚಟುವಟಿಕೆಗಳು',
    my_alerts_sos: 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು (SOS)',
    my_service_record: 'ನನ್ನ ಸೇವಾ ದಾಖಲೆ',
    unit_hierarchy: 'ಘಟಕ ಶ್ರೇಣಿ ರಚನೆ',
    sos_distress_alert: 'ತುರ್ತು ಆಪತ್ತು ಎಚ್ಚರಿಕೆ (SOS)',
    sos_active: 'ತುರ್ತು ಸಕ್ರಿಯ (ಕಮಾಂಡ್‌ಗೆ ತಿಳಿಸಲಾಗಿದೆ)',
    record_daily_checkin: 'ದೈನಂದಿನ ಚೆಕ್-ಇನ್ ದಾಖಲಿಸಿ',
    form_16_dossier: 'ಫಾರ್ಮ್ 16 ಕಲ್ಯಾಣ ದಾಖಲೆ 🖨️',
    self_assessment: 'ಸ್ವಯಂ ಮೌಲ್ಯಮಾಪನ',
    assessment_title: 'ಗೌಪ್ಯ ಮಾನಸಿಕ ಸ್ವಯಂ ಮೌಲ್ಯಮಾಪನ',

    article_42a_title: 'ವಿಧಿ 42-ಎ ರಕ್ಷಣಾ ವೈದ್ಯಕೀಯ ಗೌಪ್ಯತೆ ಸಕ್ರಿಯವಾಗಿದೆ',
    non_punitive_badge: 'ಶಿಕ್ಷಾರಹಿತ ಸುರಕ್ಷಿತ ತಾಣ',
    article_42a_desc: 'ನಿಮ್ಮ ಮಾನಸಿಕ ಡೇಟಾ ಸಂಪೂರ್ಣ ಸುರಕ್ಷಿತ ವೈದ್ಯಕೀಯ ದಾಖಲೆಯಾಗಿದೆ.',
    view_transparency_matrix: 'ಪಾರದರ್ಶಕತೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ವೀಕ್ಷಿಸಿ',
    hide_privacy_barrier: 'ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಮರೆಮಾಡಿ',
    what_doctors_see: 'ವೈದ್ಯಾಧಿಕಾರಿಗಳು ನೋಡಬಹುದಾದದ್ದು:',
    what_commanders_see: 'ಕಮಾಂಡಿಂಗ್ ಅಧಿಕಾರಿಗಳು ನೋಡಬಹುದಾದದ್ದು:',

    checkin_heading: 'ದೈನಂದಿನ ಗೌಪ್ಯ ಕ್ಷೇಮ ಚೆಕ್-ಇನ್',
    checkin_sub: 'ಕಳೆದ 24 ಗಂಟೆಗಳ ದೈಹಿಕ ಸ್ಥಿತಿಯನ್ನು ದಾಖಲಿಸಿ.',
    sleep_hours: 'ನಿದ್ರೆಯ ಗಂಟೆಗಳು (ಕಳೆದ 24 ಗಂಟೆಗಳು)',
    mental_mood: 'ಮಾನಸಿಕ ಸ್ಥಿತಿ / ಮೂಡ್',
    fatigue_level: 'ಆಯಾಸದ ಮಟ್ಟ',
    workload_strain: 'ಕಾರ್ಯಾಚರಣೆಯ ಕೆಲಸದ ಹೊರೆ',
    musculoskeletal_strain: 'ಸ್ನಾಯುಗಳ ಸೆಳೆತ',
    duty_days_without_leave: 'ರಜೆಯಿಲ್ಲದೆ ನಿರಂತರ ಕರ್ತವ್ಯದ ದಿನಗಳು',
    confidential_notes: 'ಗೌಪ್ಯ ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)',
    submit_checkin: 'ಚೆಕ್-ಇನ್ ಸಲ್ಲಿಸಿ',
    syncing: 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    checkin_success: 'ದೈನಂದಿನ ಚೆಕ್-ಇನ್ ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ!',

    wellness_score_heading: 'ವೈಯಕ್ತಿಕ ಕ್ಷೇಮ ಸ್ಕೋರ್ ಮತ್ತು ಪ್ರಮುಖ ಸೂಚಕಗಳು',
    combat_fit: 'ಕಾರ್ಯಾಚರಣೆಗೆ ಸಿದ್ಧ',
    optimal_status: 'ಉತ್ತಮ ಕಾರ್ಯಾಚರಣೆ ಸ್ಥಿತಿ',
    sleep_restoration: 'ನಿದ್ರೆಯ ಚೇತರಿಕೆ',
    fatigue_burnout: 'ದೈಹಿಕ ಆಯಾಸ ಮತ್ತು ಬಳಲಿಕೆ ಸೂಚ್ಯಂಕ',
    physical_strain: 'ದೈಹಿಕ ಶ್ರಮ',
    consecutive_duty_days: 'ನಿರಂತರ ಕರ್ತವ್ಯ ದಿನಗಳು',

    tactical_resilience: 'ಸೈನಿಕ ಬಾಕ್ಸ್ ಉಸಿರಾಟ ಪ್ರೋಟೋಕಾಲ್',
    box_breathing_desc: 'ಒತ್ತಡ ನಿಯಂತ್ರಣಕ್ಕಾಗಿ 4-4-4-4 ಮಿಲಿಟರಿ ಉಸಿರಾಟ ಅಭ್ಯಾಸ.',
    inhale: 'ಉಸಿರನ್ನು ಒಳಗೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    hold: 'ಉಸಿರನ್ನು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳಿ',
    exhale: 'ಉಸಿರನ್ನು ಹೊರಹಾಕಿ',
    pause: 'ವಿರಾಮ',
    start_protocol: 'ಪ್ರಾರಂಭಿಸಿ',
    pause_protocol: 'ನಿಲ್ಲಿಸಿ',
    reset_protocol: 'ಮರುಹೊಂದಿಸಿ',

    corps_level: 'ಕೋರ್ ಕಮಾಂಡ್',
    division_level: 'ಡಿವಿಷನ್ ಕಮಾಂಡ್',
    brigade_level: 'ಬ್ರಿಗೇಡ್ ಕಮಾಂಡ್',
    battalion_level: 'ಬಟಾಲಿಯನ್ ಮಟ್ಟ',
    company_level: 'ಕಂಪನಿ ಔಟ್‌ಪೋಸ್ಟ್',
    section_drilldown: 'ಕಮಾಂಡ್ ಸರಪಳಿ ಮತ್ತು ಪಡೆ ರಚನೆ',

    opt_never: 'ಎಂದಿಗೂ ಇಲ್ಲ',
    opt_rarely: 'ವಿರಳವಾಗಿ',
    opt_sometimes: 'ಕೆಲವೊಮ್ಮೆ',
    opt_often: 'ಆಗಾಗ್ಗೆ',
    opt_always: 'ಬಹುತೇಕ ಯಾವಾಗಲೂ',
  },

  ml: {
    defense_command: 'പ്രതിരോധ കമാൻഡ്',
    app_title: 'സൈനിക മാനസിക സമ്മർദ്ദ & ക്ഷേമ ഇന്റലിജൻസ് കമാൻഡ് സിസ്റ്റം',
    jai_hind: 'ജയ് ഹിന്ദ്',
    welcome_soldier:
      'നിങ്ങളുടെ വ്യക്തിഗത ദൈനംദിന വെൽനസ് കോക്ക്പിറ്റ്. ശാരീരിക വീണ്ടെടുക്കൽ നിരീക്ഷിക്കുകയും എഐ ആരോഗ്യ നിർദ്ദേശങ്ങൾ ലഭ്യമാക്കുകയും ചെയ്യുക.',
    personal_dashboard: 'വ്യക്തിഗത ഡാഷ്‌ബോർഡ്',
    daily_checkin: 'ദൈനംദിന ചെക്ക്-ഇൻ',
    ai_health_insights: 'എഐ ആരോഗ്യ വിവരങ്ങൾ',
    recovery_activities: 'വിശ്രമ പ്രവർത്തനങ്ങൾ',
    my_alerts_sos: 'അടിയന്തര മുന്നറിയിപ്പുകൾ (SOS)',
    my_service_record: 'എന്റെ സേവന രേഖ',
    unit_hierarchy: 'സൈനിക ഘടന വൃക്ഷം',
    sos_distress_alert: 'അടിയന്തര ആപത്ത് മുന്നറിയിപ്പ് (SOS)',
    sos_active: 'അടിയന്തരാവസ്ഥ സജീവം (കമാൻഡിനെ അറിയിച്ചു)',
    record_daily_checkin: 'ചെക്ക്-ഇൻ രേഖപ്പെടുത്തുക',
    form_16_dossier: 'ഫോം 16 ക്ഷേമ രേഖ 🖨️',
    self_assessment: 'സ്വയം വിലയിരുത്തൽ',
    assessment_title: 'രഹസ്യ മനശാസ്ത്ര സ്വയം വിലയിരുത്തൽ',

    article_42a_title: 'ആർട്ടിക്കിൾ 42-എ പ്രതിരോധ മെഡിക്കൽ രഹസ്യാത്മകത സജീവം',
    non_punitive_badge: 'ശിക്ഷാരഹിതമായ സുരക്ഷിത താവളം',
    article_42a_desc: 'നിങ്ങളുടെ മാനസികാവസ്ഥ രേഖകൾ പൂർണ്ണമായും സുരക്ഷിതമായ മെഡിക്കൽ രേഖകളാണ്.',
    view_transparency_matrix: 'സുതാര്യത മാട്രിക്സ് കാണുക',
    hide_privacy_barrier: 'മാട്രിക്സ് മറയ്ക്കുക',
    what_doctors_see: 'മെഡിക്കൽ ഓഫീസർമാർ കാണുന്നത്:',
    what_commanders_see: 'കമാൻഡിംഗ് ഓഫീസർമാർ കാണുന്നത്:',

    checkin_heading: 'ദൈനംദിന രഹസ്യ വെൽനസ് ചെക്ക്-ഇൻ',
    checkin_sub: 'കഴിഞ്ഞ 24 മണിക്കൂറിലെ ശാരീരികാവസ്ഥ രേഖപ്പെടുത്തുക.',
    sleep_hours: 'ഉറക്ക സമയം (കഴിഞ്ഞ 24 മണിക്കൂർ)',
    mental_mood: 'മാനസികാവസ്ഥ / മൂഡ്',
    fatigue_level: 'ക്ഷീണത്തിന്റെ അളവ്',
    workload_strain: 'ജോലിഭാരം',
    musculoskeletal_strain: 'പേശി വേദന',
    duty_days_without_leave: 'അവധിയില്ലാതെ ജോലി ചെയ്ത ദിവസങ്ങൾ',
    confidential_notes: 'രഹസ്യ നിരീക്ഷണങ്ങൾ (ഓപ്ഷണൽ)',
    submit_checkin: 'ചെക്ക്-ഇൻ സമർപ്പിക്കുക',
    syncing: 'സിങ്ക് ചെയ്യുന്നു...',
    checkin_success: 'ദൈനംദിന ചെക്ക്-ഇൻ വിജയകരമായി രേഖപ്പെടുത്തി!',

    wellness_score_heading: 'വ്യക്തിഗത വെൽനസ് സ്കോറും പ്രധാന സൂചകങ്ങളും',
    combat_fit: 'ദൗത്യത്തിന് സജ്ജം',
    optimal_status: 'ഏറ്റവും മികച്ച പ്രവർത്തന നില',
    sleep_restoration: 'ഉറക്ക വീണ്ടെടുക്കൽ',
    fatigue_burnout: 'ക്ഷീണവും തളർച്ചയും സൂചിക',
    physical_strain: 'ശാരീരിക അധ്വാനം',
    consecutive_duty_days: 'തുടർച്ചയായ ജോലി ദിനങ്ങൾ',

    tactical_resilience: 'ടാക്റ്റിക്കൽ ബോക്സ് ശ്വസന രീതി',
    box_breathing_desc: 'സമ്മർദ്ദം നിയന്ത്രിക്കുന്നതിനുള്ള 4-4-4-4 സൈനിക ശ്വസന വ്യായാമം.',
    inhale: 'ശ്വാസമെടുക്കുക',
    hold: 'ശ്വാസം അടക്കിപ്പിടിക്കുക',
    exhale: 'ശ്വാസം പുറത്തുവിടുക',
    pause: 'വിശ്രമം',
    start_protocol: 'ആരംഭിക്കുക',
    pause_protocol: 'നിർത്തുക',
    reset_protocol: 'റീസെറ്റ് ചെയ്യുക',

    corps_level: 'കോർ കമാൻഡ്',
    division_level: 'ഡിവിഷൻ കമാൻഡ്',
    brigade_level: 'ബ്രിഗേഡ് കമാൻഡ്',
    battalion_level: 'ബറ്റാലിയൻ തലം',
    company_level: 'കമ്പനി ഔട്ട്പോസ്റ്റ്',
    section_drilldown: 'കമാൻഡ് ശൃംഖലയും സേനാ ഘടനയും',

    opt_never: 'ഒരിക്കലുമില്ല',
    opt_rarely: 'വല്ലപ്പോഴും',
    opt_sometimes: 'ചിലപ്പോൾ',
    opt_often: 'പലപ്പോഴും',
    opt_always: 'മിക്കവാറും എപ്പോഴും',
  },

  or: {
    defense_command: 'ପ୍ରତିରକ୍ଷା କମାଣ୍ଡ',
    app_title: 'ସୈନିକ ଚାପ ଓ କଲ୍ୟାଣ ଗୋଇନ୍ଦା କମାଣ୍ଡ ପ୍ରଣାଳୀ',
    jai_hind: 'ଜୟ ହିନ୍ଦ',
    welcome_soldier:
      'ଆପଣଙ୍କର ବ୍ୟକ୍ତିଗତ ଦୈନନ୍ଦିନ ସୁସ୍ଥତା କକ୍‌ପିଟ୍। ଶାରୀରିକ ସୁସ୍ଥତା ଟ୍ରାକ୍ କରନ୍ତୁ ଏବଂ ଏଆଇ ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶ ପାଆନ୍ତୁ।',
    personal_dashboard: 'ବ୍ୟକ୍ତିଗତ ଡ୍ୟାସବୋର୍ଡ',
    daily_checkin: 'ଦୈନନ୍ଦିନ ଚେକ୍-ଇନ୍',
    ai_health_insights: 'ଏଆଇ ସ୍ୱାସ୍ଥ୍ୟ ଅନ୍ତର୍ଦୃଷ୍ଟି',
    recovery_activities: 'ପୁନରୁଦ୍ଧାର କାର୍ଯ୍ୟକଳାପ',
    my_alerts_sos: 'ଜରୁରୀକାଳୀନ ସତର୍କତା (SOS)',
    my_service_record: 'ମୋର ସେବା ରେକର୍ଡ',
    unit_hierarchy: 'ୟୁନିଟ୍ ଶ୍ରେଣୀବଦ୍ଧ ଗଠନ',
    sos_distress_alert: 'ଜରୁରୀକାଳୀନ ସଙ୍କଟ ସତର୍କତା (SOS)',
    sos_active: 'ଜରୁରୀକାଳୀନ ସକ୍ରିୟ (କମାଣ୍ଡକୁ ସୂଚନା ଦିଆଯାଇଛି)',
    record_daily_checkin: 'ଦୈନିକ ଚେକ୍-ଇନ୍ ଦାଖଲ କରନ୍ତୁ',
    form_16_dossier: 'ଫର୍ମ ୧୬ କଲ୍ୟାଣ ଡୋସିୟର 🖨️',
    self_assessment: 'ଆତ୍ମ-ମୂଲ୍ୟାଙ୍କନ',
    assessment_title: 'ଗୋପନୀୟ ମନସ୍ତାତ୍ତ୍ୱିକ ଆତ୍ମ-ମୂଲ୍ୟାଙ୍କନ',

    article_42a_title: 'ଧାରା ୪୨-ଏ ପ୍ରତିରକ୍ଷା ଚିକିତ୍ସା ଅଧିକାର ଓ ଆଇନଗତ ଗୋପନୀୟତା ସକ୍ରିୟ',
    non_punitive_badge: 'ଦଣ୍ଡମୁକ୍ତ ସୁରକ୍ଷିତ ଆଶ୍ରୟ',
    article_42a_desc: 'ଆପଣଙ୍କର ମାନସିକ ସ୍ୱାସ୍ଥ୍ୟ ତଥ୍ୟ ଆଇନଗତ ଭାବେ ସୁରକ୍ଷିତ ଡାକ୍ତରୀ ରେକର୍ଡ ଅଟେ।',
    view_transparency_matrix: 'ସ୍ୱଚ୍ଛତା ମ୍ୟାଟ୍ରିକ୍ସ ଦେଖନ୍ତୁ',
    hide_privacy_barrier: 'ମ୍ୟାଟ୍ରିକ୍ସ ଲୁଚାନ୍ତୁ',
    what_doctors_see: 'ଡାକ୍ତରୀ ଅଧିକାରୀମାନେ କ’ଣ ଦେଖିପାରିବେ:',
    what_commanders_see: 'କମାଣ୍ଡିଂ ଅଫିସର କ’ଣ ଦେଖିବେ:',

    checkin_heading: 'ଦୈନନ୍ଦିନ ଗୋପନୀୟ ସ୍ୱାସ୍ଥ୍ୟ ଚେକ୍-ଇନ୍',
    checkin_sub: 'ଗତ ୨୪ ଘଣ୍ଟାର ଶାରୀରିକ ସ୍ଥିତି ଲିପିବଦ୍ଧ କରନ୍ତୁ।',
    sleep_hours: 'ନିଦ୍ରା ସମୟ (ବିଗତ ୨୪ ଘଣ୍ଟା)',
    mental_mood: 'ମାନସିକ ସ୍ଥିତି / ମନୋଭାବ',
    fatigue_level: 'କ୍ଳାନ୍ତିର ସ୍ତର',
    workload_strain: 'କାର୍ଯ୍ୟଭାର ଚାପ',
    musculoskeletal_strain: 'ମାଂସପେଶୀର ଯନ୍ତ୍ରଣା',
    duty_days_without_leave: 'ଛୁଟି ବିନା କ୍ରମାଗତ ଡ୍ୟୁଟି ଦିବସ',
    confidential_notes: 'ଗୋପନୀୟ ଟିପ୍ପଣୀ (ଇଚ୍ଛାଧୀନ)',
    submit_checkin: 'ଚେକ୍-ଇନ୍ ଦାଖଲ କରନ୍ତୁ',
    syncing: 'ସିଙ୍କ୍ ହେଉଛି...',
    checkin_success: 'ଦୈନିକ ଚେକ୍-ଇନ୍ ସଫଳତାର ସହ ପଞ୍ଜୀକୃତ ହେଲା!',

    wellness_score_heading: 'ବ୍ୟକ୍ତିଗତ ସୁସ୍ଥତା ସ୍କୋର ଏବଂ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସଙ୍କେତ',
    combat_fit: 'ଯୁଦ୍ଧ ପାଇଁ ପ୍ରସ୍ତୁତ',
    optimal_status: 'ସର୍ବୋତ୍ତମ ପରିଚାଳନା ସ୍ଥିତି',
    sleep_restoration: 'ନିଦ୍ରା ପୁନରୁଦ୍ଧାର',
    fatigue_burnout: 'କ୍ଳାନ୍ତି ଓ ଅବସାଦ ସୂଚକାଙ୍କ',
    physical_strain: 'ଶାରୀରିକ ଚାପ',
    consecutive_duty_days: 'କ୍ରମାଗତ ଡ୍ୟୁଟି ଦିବସ',

    tactical_resilience: 'ସାମରିକ ବକ୍ସ ଶ୍ୱାସ ପ୍ରଶ୍ୱାସ ବ୍ୟାୟାମ',
    box_breathing_desc: 'ଚାପ ନିୟନ୍ତ୍ରଣ ପାଇଁ ୪-୪-୪-୪ ସେକେଣ୍ଡର ସାମରିକ ଶ୍ୱାସକ୍ରିୟା।',
    inhale: 'ଶ୍ୱାସ ନିଅନ୍ତୁ',
    hold: 'ଧରି ରଖନ୍ତୁ',
    exhale: 'ଶ୍ୱାସ ଛାଡ଼ନ୍ତୁ',
    pause: 'ବିରାମ ଦିଅନ୍ତୁ',
    start_protocol: 'ଆରମ୍ଭ କରନ୍ତୁ',
    pause_protocol: 'ବନ୍ଦ କରନ୍ତୁ',
    reset_protocol: 'ପୁନଃ ସେଟ୍ କରନ୍ତୁ',

    corps_level: 'କୋର କମାଣ୍ଡ',
    division_level: 'ଡିଭିଜନ କମାଣ୍ଡ',
    brigade_level: 'ବ୍ରିଗେଡ କମାଣ୍ଡ',
    battalion_level: 'ବ୍ୟାଟାଲିୟନ ସ୍ତର',
    company_level: 'କମ୍ପାନୀ ଆଉଟପୋଷ୍ଟ',
    section_drilldown: 'କମାଣ୍ଡ ଶୃଙ୍ଖଳା ଓ ବଳ ଗଠନ',

    opt_never: 'କେବେ ନୁହେଁ',
    opt_rarely: 'କ୍ବଚିତ୍',
    opt_sometimes: 'କେବେ କେବେ',
    opt_often: 'ପ୍ରାୟତଃ',
    opt_always: 'ପ୍ରାୟ ସବୁବେଳେ',
  },
};

export const COMMON_PHRASE_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {},
  hi: {
    // Navigation & Shell
    'PRIMARY MODULES': 'मुख्य मॉड्यूल',
    'Command Modules': 'कमान मॉड्यूल',
    'Primary Modules': 'मुख्य मॉड्यूल',
    'ROLE DISPATCH': 'भूमिका चयन',
    'Role Dispatch': 'भूमिका चयन',
    'Change Profile': 'प्रोफ़ाइल बदलें',
    'Switch': 'बदलें',
    'Defense Grade RBAC': 'रक्षा स्तरीय सुरक्षा (RBAC)',
    'Active session verified with 256-bit cryptographic tokens.': '256-बिट क्रिप्टोग्राफ़िक टोकन के साथ सक्रिय सत्र सत्यापित।',
    'Gateway Active': 'गेटवे सक्रिय',
    'Chief Welfare Officer': 'मुख्य कल्याण अधिकारी',
    'Formation Commander': 'फॉर्मेशन कमांडर',
    'Senior HR Superintendent': 'वरिष्ठ एचआर अधीक्षक',
    'Frontline Personnel': 'अग्रिम पंक्ति के जवान',
    'System Administrator': 'सिस्टम प्रशासक',
    'Authorized Personnel': 'अधिकृत कार्मिक',
    'Dashboard': 'डैशबोर्ड',
    'Personal Dashboard': 'व्यक्तिगत डैशबोर्ड',
    'Unit Hierarchy': 'सैन्य पदानुक्रम',
    'Unit Hierarchy Tree': 'सैन्य पदानुक्रम वृक्ष',
    'Personnel Overview': 'कार्मिक अवलोकन',
    'Force Overview': 'बल अवलोकन',
    'Personnel Directory': 'कार्मिक निर्देशिका',
    'Risk Analysis': 'जोखिम विश्लेषण',
    'Unit Analysis': 'इकाई विश्लेषण',
    'AI Predictions': 'एआई भविष्यवाणियां',
    'AI Insights': 'एआई अंतर्दृष्टि',
    'Welfare Actions': 'कल्याणकारी कार्रवाइयां',
    'Reports & Analytics': 'रिपोर्ट एवं विश्लेषण',
    'Reports': 'रिपोर्ट्स',
    'Resource Center': 'संसाधन केंद्र',
    'Resources': 'संसाधन',
    'Settings': 'सेटिंग्स',
    'Log Out': 'लॉग आउट',
    'Secure Sign Out': 'सुरक्षित साइन आउट',
    'Switch Role Profile': 'भूमिका प्रोफ़ाइल बदलें',
    'DEFENSE COMMAND': 'रक्षा कमान',
    'Personnel Stress & Welfare Intelligence Command': 'सैनिक तनाव एवं कल्याण आसूचना कमान',

    // Welfare Dashboard Banner
    'AI Welfare Intelligence Center': 'एआई कल्याण आसूचना केंद्र',
    'For a Stronger Force, A Healthier Tomorrow': 'सशक्त सेना, स्वस्थ कल के लिए',
    'A Healthy Soldier • A Stronger Nation': '“स्वस्थ सैनिक • सशक्त राष्ट्र”',
    'Command Welfare Doctrine': 'कमान कल्याण सिद्धांत',
    'SERVICE • SECURITY • SELFLESSNESS': 'सेवा • सुरक्षा • निःस्वार्थता',
    'Northern Command': 'उत्तरी कमान',
    'Welfare Officer': 'कल्याण अधिकारी',

    // Filters & Search
    'Search personnel by Name, JC/Regimental No, Rank, Unit or Branch': 'नाम, जेसी/रेजिमेंटल नंबर, पद, यूनिट या शाखा द्वारा खोजें...',
    'All Personnel': 'समस्त कर्मी',
    'All': 'समस्त',
    'Critical': 'गंभीर',
    'High': 'उच्च',
    'Moderate': 'मध्यम',
    'Nominal': 'सामान्य',
    'Risk': 'जोखिम',
    'Critical Risk': 'गंभीर जोखिम',
    'High Risk': 'उच्च जोखिम',
    'Moderate Risk': 'मध्यम जोखिम',
    'Nominal Risk': 'सामान्य जोखिम',
    'Currently Selected Profile:': 'वर्तमान चयनित प्रोफ़ाइल:',
    'Telemetry & Psychometric Analysis Synchronized': 'टेलीमेट्री एवं मनोवैज्ञानिक विश्लेषण सिंक्रनाइज़्ड',

    // KPI Cards
    'Operational Readiness': 'परिचालन तत्परता',
    'Force readiness on positive trend': 'सकारात्मक रुझान पर बल की तैयारी',
    'Personnel Requiring Support': 'सहायता की आवश्यकता वाले कर्मी',
    'Need immediate attention': 'तत्काल ध्यान देने की आवश्यकता',
    'High priority cases': 'उच्च प्राथमिकता वाले मामले',
    'Pending Welfare Actions': 'लंबित कल्याणकारी कार्रवाइयां',
    'Awaiting closure': 'समापन की प्रतीक्षा में',
    'Follow up required': 'अनुवर्ती कार्रवाई अपेक्षित',
    'Average Wellness Score': 'औसत कल्याण स्कोर',
    'Improving trend': 'सुधार का रुझान',
    'Across all personnel': 'समस्त कर्मियों में',
    'vs last month': 'विगत माह की तुलना में',

    // Critical Welfare Alert Hero
    'Critical Welfare Alert': 'गंभीर कल्याण चेतावनी',
    'HIGH PRIORITY': 'उच्च प्राथमिकता',
    'TREND (LAST 3 MONTHS)': 'रुझान (विगत 3 माह)',
    'Trend (Last 3 Months)': 'रुझान (विगत 3 माह)',
    'PREDICTION CONFIDENCE': 'पूर्वानुमान विश्वास',
    'Prediction Confidence': 'पूर्वानुमान विश्वास',
    'LAST UPDATED': 'अंतिम अद्यतन',
    'Last Updated': 'अंतिम अद्यतन',
    'Root-Cause Stress Diagnosis': 'मूल कारण तनाव निदान',
    'Triggers:': 'उत्प्रेरक कारक:',
    'Predictive Disaster Horizon': 'भविष्य कहने वाला संकट क्षितिज',
    'Tailored Action Protocol': 'अनुकूलित कार्य प्रोटोकॉल',
    'Initiate Protocol Action': 'प्रोटोकॉल कार्रवाई शुरू करें',
    'Initiate Directive': 'निर्देश प्रारंभ करें',
    'Dispatch All Directives': 'समस्त निर्देश प्रेषित करें',
    'Risk Score': 'जोखिम स्कोर',
    'Field Unit:': 'फील्ड यूनिट:',
    'Location:': 'स्थान:',
    'Welfare Priority': 'कल्याण प्राथमिकता',
    'Early-Warning Pre-Prediction: Stress, Burnout & Presenteeism Timeline': 'पूर्व-चेतावनी पूर्वानुमान: तनाव, बर्नआउट एवं प्रजेंटियिज़्म समयसीमा',
    'Projected Disaster:': 'अनुमानित संकट:',
    'Anticipated Clinical Failure Mode:': 'अपेक्षित क्लीनिकल विफलता स्वरूप:',
    'Prevention Window:': 'रोकथाम समयसीमा:',
    'Cascade Forecast:': 'क्रमिक संकट पूर्वानुमान:',
    'Presenteeism Diagnosis:': 'प्रजेंटियिज़्म निदान:',
    'Burnout Collapse Probability': 'बर्नआउट पतन की संभावना',
    'Presenteeism Index (Hidden Stress)': 'प्रजेंटियिज़्म सूचकांक (अदृश्य तनाव)',
    'Progression Trajectory: Day 0 → Day 30': 'प्रगति प्रक्षेपवक्र: दिन 0 → दिन 30',
    'Actions': 'कार्रवाइयां',
    'Step': 'चरण',
    'of': 'का',

    // Risk Forecasting & Sections
    'Risk Forecasting': 'जोखिम पूर्वानुमान',
    'ML Predictive Engine': 'एमएल प्रेडिक्टिव इंजन',
    'Current Risk': 'वर्तमान जोखिम',
    '30-Day Shift': '30-दिवसीय परिवर्तन',
    'Predicted in 30 Days': '30 दिनों में अनुमानित',
    '30-Day Longitudinal Stress Trajectory': '30-दिवसीय दीर्घकालिक तनाव प्रक्षेपवक्र',
    'Visualization': 'दृश्यीकरण (ग्राफ़)',
    'Milestones': 'मील के पत्थर',
    'Live Telemetry Baseline Assessment': 'लाइव टेलीमेट्री बेसलाइन मूल्यांकन',
    'ML Projected Cognitive & Physiological Load': 'एमएल अनुमानित संज्ञानात्मक एवं शारीरिक भार',
    'AI Health Modules': 'एआई स्वास्थ्य मॉड्यूल',
    'Top Contributing Factors (Explainable AI)': 'प्रमुख योगदान कारक (व्याख्या योग्य एआई)',
    'Risk Trend (Last 6 Months)': 'जोखिम रुझान (विगत 6 माह)',
    'Personnel Risk Distribution': 'कार्मिक जोखिम वितरण',
    'Priority Personnel Queue': 'प्राथमिकता कार्मिक कतार',
    'Recent Welfare Interventions': 'हालिया कल्याण हस्तक्षेप',
    'Privacy & Ethical Use': 'गोपनीयता एवं नैतिक उपयोग',

    // Commander Dashboard
    'Command Echelon Access Scope • Aggregated Readiness Only': 'कमान स्तर पहुंच — केवल समग्र तत्परता',
    'Strict RBAC Boundary': 'कड़ी भूमिका-आधारित सुरक्षा सीमा',
    'Confidentiality Safeguard:': 'गोपनीयता सुरक्षा:',
    'Medical Airgap Enforced': 'चिकित्सा एयरगैप लागू',
    'Emotional Stability Index': 'भावनात्मक स्थिरता सूचकांक',
    'Command Intelligence': 'कमान आसूचना',
    'Unit Output Benchmark': 'इकाई उत्पादन बेंचमार्क',
    'Division Aggregation': 'डिवीज़न समग्र',
    'Stable': 'स्थिर',
    'High Affective Consistency': 'उच्च भावनात्मक स्थिरता',
    'Volatility Standard Deviation:': 'अस्थिरता मानक विचलन:',
    'Active Duty Threshold:': 'सक्रिय ड्यूटी सीमा:',
    'Command Assessment:': 'कमान मूल्यांकन:',
    'Algorithm Inputs / 6-Factor Multi-Modal Telemetry': 'एल्गोरिदम इनपुट / 6-कारक मल्टी-मोडल टेलीमेट्री',
    'Weights Sum: 100%': 'भार योग: 100%',
    '7-Day Trajectory:': '7-दिन प्रक्षेपवक्र:',
    'Consistency Variance: Minimal': 'निरंतरता भिन्नता: न्यूनतम',
    'Behavioral Change Detection': 'व्यवहार परिवर्तन पहचान',
    'Anomaly Surveillance': 'विसंगति निगरानी',
    'Comparison Window': 'तुलना विंडो',
    '14-Day Current vs 90-Day Baseline': '14-दिन वर्तमान बनाम 90-दिन आधार रेखा',
    '14 High-Shift Anomaly Flags': '14 उच्च-बदलाव विसंगति संकेत',
    'Force Anomaly Drift': 'बल विसंगति विचलन',
    'Unit Aggregate': 'इकाई समग्र',
    'Mild Unit Drift': 'हल्की इकाई विचलन',
    '89% Troops Stable': '89% सैनिक स्थिर',
    'Top Unit Outliers (Behavior Change Score)': 'शीर्ष इकाई आउटलायर (व्यवहार परिवर्तन स्कोर)',
    '5 Monitored Behavioral Domains • Current VS Historical Baseline Comparison': '5 अनुश्रवित व्यवहारिक क्षेत्र • वर्तमान बनाम ऐतिहासिक आधार रेखा',
    'Continuous ML Telemetry': 'सतत एमएल टेलीमेट्री',
    'Historical': 'ऐतिहासिक',
    'Current': 'वर्तमान',
    'Net Shift': 'शुद्ध बदलाव',
    'Executive Action:': 'कार्यकारी कार्रवाई:',
    'Rebalance Rosters': 'रोस्टर पुनः संतुलित करें',
    'Tactical Command Roster Actions & Immediate Stand-Down Queue': 'सामरिक कमान रोस्टर कार्रवाइयां एवं तत्काल स्टैंड-डाउन कतार',
    '2 Critical Fatigue Triggers': '2 गंभीर थकान ट्रिगर',
    'Critical Trigger:': 'गंभीर ट्रिगर:',
    'Tactical Replacement:': 'सामरिक प्रतिस्थापन:',
    'Executing Swap...': 'स्वैप निष्पादित हो रहा है...',
    'Approve Roster Swap & Stand-down': 'रोस्टर स्वैप एवं स्टैंड-डाउन अनुमोदित करें',
    'Approve Roster Swap & Leave Fast-Track': 'रोस्टर स्वैप एवं अवकाश फास्ट-ट्रैक अनुमोदित करें',
    'Stood Down • Sepoy Amit Deployed': 'स्टैंड-डाउन • सिपाही अमित तैनात',
    'Stood Down • Capt. Connor Deployed': 'स्टैंड-डाउन • कैप्टन कनर तैनात',
    'Unit Readiness Comparison': 'इकाई तत्परता तुलना',
    'View All →': 'सभी देखें →',
    'Click any unit to open drill-down dossier': 'ड्रिल-डाउन के लिए किसी इकाई पर क्लिक करें',
    'Operational Readiness Trend': 'परिचालन तत्परता रुझान',
    'Last 6 Months': 'पिछले 6 माह',
    'Last 30 Days': 'पिछले 30 दिन',
    'Last 1 Year': 'पिछला 1 वर्ष',
    'Force Health Radar': 'बल स्वास्थ्य रडार',
    'Previous': 'पिछला',
    'Risk Heatmap (Units vs Risk Level)': 'जोखिम हीटमैप (इकाइयां बनाम जोखिम स्तर)',
    'High Priority Units': 'उच्च प्राथमिकता इकाइयां',
    'Unit': 'इकाई',
    'Risk Level': 'जोखिम स्तर',
    'Key Concern': 'मुख्य चिंता',
    'Action': 'कार्रवाई',
    'View': 'देखें',
    'Automated Operational Psychometric Triage Queue': 'स्वचालित परिचालन मनोमितीय ट्रायज कतार',
    'AI Early Warnings': 'एआई प्रारंभिक चेतावनियां',
    'Indicator': 'संकेतक',
    'Trend': 'रुझान',
    'Predictive Horizon: Next 14 – 30 Operational Days': 'भविष्यवाणी क्षितिज: अगले 14-30 परिचालन दिन',
    'Risk Momentum & Real-Time Command Action Directives': 'जोखिम गति एवं रियल-टाइम कमान कार्रवाई निर्देश',
    'Acute Surge Alert': 'तीव्र उछाल चेतावनी',
    'Recommended Directive': 'अनुशंसित निर्देश',
    'Crit Limit:': 'महत्वपूर्ण सीमा:',
    'Directive Dispatched ✓': 'निर्देश प्रेषित ✓',
    'Open Command Decision Center →': 'कमान निर्णय केंद्र खोलें →',
    'Welfare Intervention Progress': 'कल्याण हस्तक्षेप प्रगति',
    'View Details →': 'विवरण देखें →',
    'Counselling Sessions': 'परामर्श सत्र',
    'Medical Review': 'चिकित्सा समीक्षा',
    'Duty Adjustment': 'ड्यूटी समायोजन',
    'Follow-up & Monitoring': 'अनुवर्ती एवं निगरानी',
    'Intervention Completion: 81.4% Formation Standard': 'हस्तक्षेप समापन: 81.4% संरचना मानक',
    'Resource Availability': 'संसाधन उपलब्धता',
    'Welfare Officers': 'कल्याण अधिकारी',
    'Medical Officers': 'चिकित्सा अधिकारी',
    'Counsellors': 'परामर्शदाता',
    'Mobile Clinics': 'मोबाइल क्लीनिक',
    'Available': 'उपलब्ध',
    'Operational': 'परिचालन',
    'Logistical Reserves Sufficient for 60-Day Forward Deployment': '60-दिन आगे की तैनाती के लिए पर्याप्त लॉजिस्टिकल भंडार',
    'AI Command Recommendations': 'एआई कमान अनुशंसाएं',
    'One-click directive dispatch directly to Battalion commanders': 'बटालियन कमांडरों को सीधे एक-क्लिक निर्देश प्रेषण',
    'Sent': 'भेजा गया',
    'Act': 'कार्य करें',
    'Mission Impact Metrics': 'मिशन प्रभाव मेट्रिक्स',
    'Combat Readiness Coefficient: 0.942': 'युद्ध तत्परता गुणांक: 0.942',
    'Recent Events & Timeline': 'हालिया घटनाएं एवं समयरेखा',
    'Critical alerts raised': 'गंभीर अलर्ट उठाए गए',
    'Counselling session completed (5 personnel)': 'परामर्श सत्र पूर्ण (5 कार्मिक)',
    'Workload adjustment approved for Bravo Bn': 'ब्रावो बटालियन के लिए कार्यभार समायोजन अनुमोदित',
    'Readiness improved by 4%': 'तत्परता में 4% सुधार',
    'Immutable Audit Trail Logged on HQ Server': 'एचक्यू सर्वर पर अटल ऑडिट ट्रेल दर्ज',
    'AI Executive Insight': 'एआई कार्यकारी अंतर्दृष्टि',
    'Privacy & Security': 'गोपनीयता एवं सुरक्षा',
    'Data Encrypted': 'डेटा एन्क्रिप्टेड',
    'Role-Based Access': 'भूमिका-आधारित पहुंच',
    'AI Model Audited': 'एआई मॉडल ऑडिट किया गया',
    'No Disciplinary Usage': 'कोई अनुशासनात्मक उपयोग नहीं',
    'Compliant with Data Protection Norms': 'डेटा संरक्षण मानदंडों के अनुपालन में',
    'Secure | Trusted | Welfare-Focused': 'सुरक्षित | विश्वसनीय | कल्याण-केंद्रित',
    'Deployed Strength': 'तैनात बल',
    'Primary Driver': 'प्राथमिक चालक',
    'Company Level Tactical Readiness (5 Companies)': 'कंपनी स्तर सामरिक तत्परता (5 कंपनियां)',
    'Company': 'कंपनी',
    'Risk Tier': 'जोखिम स्तर',
    'Stress Index': 'तनाव सूचकांक',
    'Troops': 'सैनिक',
    'Flagged Personnel • Risk Velocity & Action Directives': 'चिह्नित कार्मिक • जोखिम गति एवं कार्रवाई निर्देश',
    'Authorized for Formation Commander Review': 'फॉर्मेशन कमांडर समीक्षा के लिए अधिकृत',
    'Close': 'बंद करें',
    'Issue Workload Redistribution': 'कार्यभार पुनर्वितरण जारी करें',
    'Action-Oriented Command Interface': 'कार्य-उन्मुख कमान इंटरफ़ेस',
    'Execute': 'निष्पादित करें',
    'Dispatched ✓': 'प्रेषित ✓',
    'Close Decision Center': 'निर्णय केंद्र बंद करें',
    'Temporal Model': 'कालिक मॉडल',

    // HR Dashboard
    'Personnel & Records Directorate': 'कार्मिक एवं अभिलेख निदेशालय',
    'Total Active Workforce': 'कुल सक्रिय कार्यबल',
    'Personnel On Authorized Leave': 'अधिकृत अवकाश पर कार्मिक',
    'Transfers In Pipeline': 'पाइपलाइन में स्थानांतरण',
    'APAR Annual Compliance': 'एपीएआर वार्षिक अनुपालन',
    'Sync HRMS': 'एचआरएमएस सिंक करें',
    'Generate Report': 'रिपोर्ट तैयार करें',
    'HRMS Leave Applications & Rest Pipeline': 'एचआरएमएस अवकाश आवेदन एवं आराम पाइपलाइन',
    'Leave applications requiring administrative verification.': 'प्रशासनिक सत्यापन की आवश्यकता वाले अवकाश आवेदन।',
    'PENDING': 'लंबित',
    'Reason:': 'कारण:',
    'Days': 'दिन',
    'Approved by Commander': 'कमांडर द्वारा अनुमोदित',
    'Pending HR Approval': 'एचआर अनुमोदन लंबित',
    'Force Cadre Distribution': 'बल कैडर वितरण',
    'Strength allocation across rank cadres.': 'पद कैडर में बल आवंटन।',
    'HR Advisory: 18 rotation transfers submitted for upcoming quarterly posting board review.': 'एचआर सलाह: आगामी तिमाही पोस्टिंग बोर्ड समीक्षा के लिए 18 रोटेशन स्थानांतरण जमा।',
    'Syncing...': 'सिंक हो रहा है...',
    'Present Today': 'आज उपस्थित',
    'Pending Approvals': 'लंबित अनुमोदन',
    'Posting board cycle active': 'पोस्टिंग बोर्ड चक्र सक्रिय',
    'Dossier appraisals verified': 'डोजियर मूल्यांकन सत्यापित',

    // Admin Dashboard
    'Strategic System Command Console': 'सामरिक प्रणाली कमान कंसोल',
    'Provision Officer': 'अधिकारी प्रावधान करें',
    'Total Personnel in HRMS': 'एचआरएमएस में कुल कार्मिक',
    'Active Monitoring Nodes': 'सक्रिय निगरानी नोड',
    'System Uptime & Latency': 'सिस्टम अपटाइम एवं विलंब',
    'Security Audit Integrity': 'सुरक्षा ऑडिट अखंडता',
    'Synchronized via HRMS DB': 'एचआरएमएस डीबी के माध्यम से सिंक्रनाइज़',
    'Online Telemetry Stream': 'ऑनलाइन टेलीमेट्री स्ट्रीम',
    'HRMS Cryptographic Audit Trail': 'एचआरएमएस क्रिप्टोग्राफिक ऑडिट ट्रेल',
    'Real-time audit log of access events and role queries.': 'एक्सेस घटनाओं और भूमिका प्रश्नों का रियल-टाइम ऑडिट लॉग।',
    'TAMPER-PROOF LOGS': 'छेड़छाड़-रहित लॉग',
    'Platform Infrastructure': 'प्लेटफ़ॉर्म आधारभूत संरचना',
    'Live health status of microservices.': 'माइक्रोसर्विस की लाइव स्वास्थ्य स्थिति।',
    'API Gateway': 'एपीआई गेटवे',
    'Online': 'ऑनलाइन',
    'HRMS Database': 'एचआरएमएस डेटाबेस',
    'Connected': 'जुड़ा हुआ',
    'AI Stress Engine': 'एआई तनाव इंजन',
    'Active': 'सक्रिय',
    'HRMS sync engine active. Continuous bi-directional telemetry verification enabled.': 'एचआरएमएस सिंक इंजन सक्रिय। निरंतर द्विदिशीय टेलीमेट्री सत्यापन सक्षम।',
    'Synchronized Strategic Defense HRMS Management. Centralized user identity governance, cryptographic audit trails, and multi-service health diagnostics.': 'सिंक्रनाइज़ सामरिक रक्षा एचआरएमएस प्रबंधन। केंद्रीकृत उपयोगकर्ता पहचान प्रशासन, क्रिप्टोग्राफिक ऑडिट ट्रेल।',
    'Synchronized HRMS Workforce Management. Live leave application pipeline, posting distributions, attendance rosters, and APAR compliance records.': 'सिंक्रनाइज़ एचआरएमएस कार्यबल प्रबंधन। लाइव अवकाश आवेदन पाइपलाइन, पोस्टिंग वितरण, उपस्थिति रोस्टर।',
    'Welcome,': 'स्वागत है,',
  },
  pa: {
    'PRIMARY MODULES': 'ਮੁੱਖ ਮਾਡਿਊਲ',
    'Command Modules': 'ਕਮਾਂਡ ਮਾਡਿਊਲ',
    'Primary Modules': 'ਮੁੱਖ ਮਾਡਿਊਲ',
    'ROLE DISPATCH': 'ਭੂਮਿਕਾ ਚੋਣ',
    'Role Dispatch': 'ਭੂਮਿਕਾ ਚੋਣ',
    'Change Profile': 'ਪ੍ਰੋਫਾਈਲ ਬਦਲੋ',
    'Switch': 'ਬਦਲੋ',
    'Defense Grade RBAC': 'ਰੱਖਿਆ ਗ੍ਰੇਡ ਆਰਬੀਏਸੀ',
    'Active session verified with 256-bit cryptographic tokens.': '256-ਬਿੱਟ ਕ੍ਰਿਪਟੋਗ੍ਰਾਫਿਕ ਟੋਕਨਾਂ ਨਾਲ ਸੁਰੱਖਿਅਤ ਸੈਸ਼ਨ।',
    'Gateway Active': 'ਗੇਟਵੇ ਸਰਗਰਮ',
    'Chief Welfare Officer': 'ਮੁੱਖ ਭਲਾਈ ਅਧਿਕਾਰੀ',
    'Formation Commander': 'ਫਾਰਮੇਸ਼ਨ ਕਮਾਂਡਰ',
    'Senior HR Superintendent': 'ਸੀਨੀਅਰ ਐਚਆਰ ਸੁਪਰਡੈਂਟ',
    'Frontline Personnel': 'ਮੋਹਰੀ ਕਤਾਰ ਦੇ ਜਵਾਨ',
    'Dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'Unit Hierarchy': 'ਯੂਨਿਟ ਲੜੀਵਾਰ ਢਾਂਚਾ',
    'Personnel Overview': 'ਜਵਾਨਾਂ ਦੀ ਸਮੀਖਿਆ',
    'Risk Analysis': 'ਜੋਖਮ ਵਿਸ਼ਲੇਸ਼ਣ',
    'AI Predictions': 'ਏਆਈ ਭਵਿੱਖਬਾਣੀਆਂ',
    'Welfare Actions': 'ਭਲਾਈ ਕਾਰਵਾਈਆਂ',
    'Reports & Analytics': 'ਰਿਪੋਰਟਾਂ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ',
    'Resource Center': 'ਸਰੋਤ ਕੇਂਦਰ',
    'Settings': 'ਸੈਟਿੰਗਾਂ',
    'Log Out': 'ਲਾਗ ਆਊਟ',
    'AI Welfare Intelligence Center': 'ਏਆਈ ਭਲਾਈ ਇੰਟੈਲੀਜੈਂਸ ਕੇਂਦਰ',
    'For a Stronger Force, A Healthier Tomorrow': 'ਮਜ਼ਬੂਤ ਸੈਨਾ, ਸਿਹਤਮੰਦ ਕੱਲ੍ਹ ਲਈ',
    'A Healthy Soldier • A Stronger Nation': '“ਸਿਹਤਮੰਦ ਜਵਾਨ • ਮਜ਼ਬੂਤ ਦੇਸ਼”',
    'Operational Readiness': 'ਕਾਰਜਸ਼ੀਲ ਤਿਆਰੀ',
    'Personnel Requiring Support': 'ਸਹਾਇਤਾ ਦੀ ਲੋੜ ਵਾਲੇ ਜਵਾਨ',
    'Pending Welfare Actions': 'ਬਕਾਇਆ ਭਲਾਈ ਕਾਰਵਾਈਆਂ',
    'Average Wellness Score': 'ਔਸਤ ਵੈਲਨੈੱਸ ਸਕੋਰ',
    'All Personnel': 'ਸਾਰੇ ਜਵਾਨ',
    'Critical Risk': 'ਗੰਭੀਰ ਜੋਖਮ',
    'High Risk': 'ਉੱਚ ਜੋਖਮ',
    'Moderate Risk': 'ਮੱਧਮ ਜੋਖਮ',
    'Nominal Risk': 'ਸਧਾਰਨ ਜੋਖਮ',
    'Currently Selected Profile:': 'ਮੌਜੂਦਾ ਚੁਣੀ ਗਈ ਪ੍ਰੋਫਾਈਲ:',
    'Emotional Stability Index': 'ਭਾਵਨਾਤਮਕ ਸਥਿਰਤਾ ਸੂਚਕਾਂਕ',
    'Command Intelligence': 'ਕਮਾਂਡ ਖੁਫੀਆ ਜਾਣਕਾਰੀ',
    'Behavioral Change Detection': 'ਵਿਵਹਾਰ ਤਬਦੀਲੀ ਖੋਜ',
    'Anomaly Surveillance': 'ਵਿਸੰਗਤੀ ਨਿਗਰਾਨੀ',
    'Stable': 'ਸਥਿਰ',
    'Historical': 'ਇਤਿਹਾਸਕ',
    'Current': 'ਮੌਜੂਦਾ',
    'Net Shift': 'ਕੁੱਲ ਬਦਲਾਅ',
    'Rebalance Rosters': 'ਰੋਸਟਰ ਮੁੜ-ਸੰਤੁਲਿਤ ਕਰੋ',
    'Unit Readiness Comparison': 'ਯੂਨਿਟ ਤਿਆਰੀ ਤੁਲਨਾ',
    'View All →': 'ਸਾਰੇ ਵੇਖੋ →',
    'Operational Readiness Trend': 'ਕਾਰਜਸ਼ੀਲ ਤਿਆਰੀ ਰੁਝਾਨ',
    'Force Health Radar': 'ਫੋਰਸ ਸਿਹਤ ਰਡਾਰ',
    'Risk Heatmap (Units vs Risk Level)': 'ਜੋਖਮ ਹੀਟਮੈਪ',
    'High Priority Units': 'ਉੱਚ ਤਰਜੀਹ ਯੂਨਿਟ',
    'AI Early Warnings': 'ਏਆਈ ਮੁਢਲੀਆਂ ਚੇਤਾਵਨੀਆਂ',
    'AI Command Recommendations': 'ਏਆਈ ਕਮਾਂਡ ਸਿਫ਼ਾਰਸ਼ਾਂ',
    'Welfare Intervention Progress': 'ਭਲਾਈ ਦਖਲ ਦੀ ਪ੍ਰਗਤੀ',
    'Resource Availability': 'ਸਰੋਤ ਉਪਲਬਧਤਾ',
    'Mission Impact Metrics': 'ਮਿਸ਼ਨ ਪ੍ਰਭਾਵ ਮੈਟ੍ਰਿਕਸ',
    'AI Executive Insight': 'ਏਆਈ ਕਾਰਜਕਾਰੀ ਸੂਝ',
    'Privacy & Security': 'ਗੋਪਨੀਯਤਾ ਅਤੇ ਸੁਰੱਖਿਆ',
    'Execute': 'ਲਾਗੂ ਕਰੋ',
    'Close': 'ਬੰਦ ਕਰੋ',
    'Deployed Strength': 'ਤਾਇਨਾਤ ਤਾਕਤ',
    'Available': 'ਉਪਲਬਧ',
    'Syncing...': 'ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...',
    'Personnel & Records Directorate': 'ਕਾਰਮਿਕ ਅਤੇ ਰਿਕਾਰਡ ਡਾਇਰੈਕਟੋਰੇਟ',
    'Total Active Workforce': 'ਕੁੱਲ ਸਰਗਰਮ ਕਾਰਜਬਲ',
    'Personnel On Authorized Leave': 'ਅਧਿਕਾਰਤ ਛੁੱਟੀ ਤੇ ਕਾਰਮਿਕ',
    'Transfers In Pipeline': 'ਪਾਈਪਲਾਈਨ ਵਿੱਚ ਤਬਾਦਲੇ',
    'APAR Annual Compliance': 'ਏਪੀਏਆਰ ਸਾਲਾਨਾ ਪਾਲਣਾ',
    'Sync HRMS': 'ਐਚਆਰਐਮਐਸ ਸਿੰਕ ਕਰੋ',
    'Generate Report': 'ਰਿਪੋਰਟ ਬਣਾਓ',
    'Force Cadre Distribution': 'ਫੋਰਸ ਕੈਡਰ ਵੰਡ',
    'PENDING': 'ਬਕਾਇਆ',
    'Welcome,': 'ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ,',
    'Strategic System Command Console': 'ਰਣਨੀਤਕ ਪ੍ਰਣਾਲੀ ਕਮਾਂਡ ਕੰਸੋਲ',
    'Provision Officer': 'ਅਧਿਕਾਰੀ ਦਾ ਪ੍ਰਬੰਧ ਕਰੋ',
    'Total Personnel in HRMS': 'ਐਚਆਰਐਮਐਸ ਵਿੱਚ ਕੁੱਲ ਕਾਰਮਿਕ',
    'HRMS Cryptographic Audit Trail': 'ਐਚਆਰਐਮਐਸ ਕ੍ਰਿਪਟੋਗ੍ਰਾਫਿਕ ਆਡਿਟ ਟ੍ਰੇਲ',
    'Platform Infrastructure': 'ਪਲੇਟਫਾਰਮ ਬੁਨਿਆਦੀ ਢਾਂਚਾ',
    'API Gateway': 'ਏਪੀਆਈ ਗੇਟਵੇ',
    'Online': 'ਔਨਲਾਈਨ',
    'HRMS Database': 'ਐਚਆਰਐਮਐਸ ਡੇਟਾਬੇਸ',
    'Connected': 'ਜੁੜਿਆ ਹੋਇਆ',
    'AI Stress Engine': 'ਏਆਈ ਤਣਾਅ ਇੰਜਣ',
    'Active': 'ਸਰਗਰਮ',
  },
  bn: {
    'PRIMARY MODULES': 'প্রধান মডিউলসমূহ',
    'Command Modules': 'কমান্ড মডিউল',
    'Primary Modules': 'প্রধান মডিউলসমূহ',
    'ROLE DISPATCH': 'ভূমিকা নির্ধারণ',
    'Role Dispatch': 'ভূমিকা নির্ধারণ',
    'Change Profile': 'প্রোফাইল পরিবর্তন',
    'Switch': 'বদলান',
    'Defense Grade RBAC': 'প্রতিরক্ষা গ্রেড আরবিএসি',
    'Active session verified with 256-bit cryptographic tokens.': '২৫৬-বিট ক্রিপ্টোগ্রাফিক টোকেন দিয়ে সক্রিয় সেশন যাচাইকৃত।',
    'Gateway Active': 'গেটওয়ে সক্রিয়',
    'Chief Welfare Officer': 'প্রধান কল্যাণ কর্মকর্তা',
    'Formation Commander': 'ফরমেশন কমান্ডার',
    'Dashboard': 'ড্যাশবোর্ড',
    'Unit Hierarchy': 'ইউনিট শ্রেণিবিন্যাস',
    'Personnel Overview': 'কর্মী পর্যবেক্ষণ',
    'Risk Analysis': 'ঝুঁকি বিশ্লেষণ',
    'AI Predictions': 'এআই পূর্বাভাস',
    'Welfare Actions': 'কল্যাণমূলক পদক্ষেপ',
    'Reports & Analytics': 'প্রতিবেদন ও বিশ্লেষণ',
    'Resource Center': 'রিসোর্স সেন্টার',
    'Settings': 'সেটিংস',
    'AI Welfare Intelligence Center': 'এআই কল্যাণ গোয়েন্দা কেন্দ্র',
    'Operational Readiness': 'কার্যক্ষম প্রস্তুতি',
    'Personnel Requiring Support': 'সহায়তা প্রয়োজন এমন কর্মী',
    'Pending Welfare Actions': 'বিচারাধীন কল্যাণমূলক পদক্ষেপ',
    'Average Wellness Score': 'গড় সুস্থতা স্কোর',
    'All Personnel': 'সকল কর্মী',
    'Critical Risk': 'সংকটপূর্ণ ঝুঁকি',
    'High Risk': 'উচ্চ ঝুঁকি',
    'Moderate Risk': 'মাঝারি ঝুঁকি',
    'Nominal Risk': 'স্বাভাবিক ঝুঁকি',
    'Emotional Stability Index': 'মানসিক স্থিতিশীলতা সূচক',
    'Command Intelligence': 'কমান্ড গোয়েন্দা তথ্য',
    'Behavioral Change Detection': 'আচরণগত পরিবর্তন সনাক্তকরণ',
    'Stable': 'স্থিতিশীল',
    'Historical': 'ঐতিহাসিক',
    'Current': 'বর্তমান',
    'Rebalance Rosters': 'রোস্টার পুনর্বিন্যাস করুন',
    'Unit Readiness Comparison': 'ইউনিট প্রস্তুতি তুলনা',
    'View All →': 'সব দেখুন →',
    'Force Health Radar': 'ফোর্স স্বাস্থ্য রাডার',
    'High Priority Units': 'উচ্চ অগ্রাধিকার ইউনিট',
    'AI Early Warnings': 'এআই প্রাথমিক সতর্কতা',
    'AI Command Recommendations': 'এআই কমান্ড সুপারিশ',
    'Welfare Intervention Progress': 'কল্যাণ হস্তক্ষেপের অগ্রগতি',
    'Resource Availability': 'সম্পদ প্রাপ্যতা',
    'Mission Impact Metrics': 'মিশন প্রভাব মেট্রিক্স',
    'AI Executive Insight': 'এআই নির্বাহী অন্তর্দৃষ্টি',
    'Privacy & Security': 'গোপনীয়তা ও নিরাপত্তা',
    'Execute': 'কার্যকর করুন',
    'Close': 'বন্ধ করুন',
    'Available': 'উপলব্ধ',
    'Syncing...': 'সিঙ্ক হচ্ছে...',
    'Total Active Workforce': 'মোট সক্রিয় কর্মশক্তি',
    'Personnel On Authorized Leave': 'অনুমোদিত ছুটিতে কর্মী',
    'Transfers In Pipeline': 'পাইপলাইনে বদলি',
    'APAR Annual Compliance': 'এপিএআর বার্ষিক সম্মতি',
    'Sync HRMS': 'এইচআরএমএস সিঙ্ক করুন',
    'Generate Report': 'রিপোর্ট তৈরি করুন',
    'Force Cadre Distribution': 'ফোর্স ক্যাডার বিতরণ',
    'PENDING': 'মুলতুবি',
    'Welcome,': 'স্বাগতম,',
    'HRMS Cryptographic Audit Trail': 'এইচআরএমএস ক্রিপ্টোগ্রাফিক অডিট ট্রেইল',
    'Platform Infrastructure': 'প্ল্যাটফর্ম পরিকাঠামো',
    'API Gateway': 'এপিআই গেটওয়ে',
    'Online': 'অনলাইন',
    'HRMS Database': 'এইচআরএমএস ডেটাবেস',
    'Connected': 'সংযুক্ত',
    'AI Stress Engine': 'এআই স্ট্রেস ইঞ্জিন',
    'Active': 'সক্রিয়',
  },
  ta: {
    'PRIMARY MODULES': 'முதன்மை தொகுதிகள்',
    'Command Modules': 'கட்டளை தொகுதிகள்',
    'Primary Modules': 'முதன்மை தொகுதிகள்',
    'ROLE DISPATCH': 'பணி தேர்வு',
    'Role Dispatch': 'பணி தேர்வு',
    'Change Profile': 'சுயவிவரத்தை மாற்றுக',
    'Switch': 'மாற்று',
    'Defense Grade RBAC': 'பாதுகாப்பு தர அணுகல்',
    'Gateway Active': 'நுழைவாயில் இயங்குகிறது',
    'Chief Welfare Officer': 'தலைமை நல அதிகாரி',
    'Dashboard': 'டாஷ்போர்டு',
    'Unit Hierarchy': 'படைப்பிரிவு படிநிலை',
    'Personnel Overview': 'பணியாளர் விவரம்',
    'Risk Analysis': 'இடர் பகுப்பாய்வு',
    'AI Predictions': 'ஏஐ கணிப்புகள்',
    'Welfare Actions': 'நலத்திட்ட நடவடிக்கைகள்',
    'Reports & Analytics': 'அறிக்கைகள் & பகுப்பாய்வு',
    'Resource Center': 'வள மையம்',
    'Settings': 'அமைப்புகள்',
    'AI Welfare Intelligence Center': 'ஏஐ நல நுண்ணறிவு மையம்',
    'Operational Readiness': 'செயல்பாட்டு தயார்நிலை',
    'Personnel Requiring Support': 'உதவி தேவைப்படும் வீரர்கள்',
    'Pending Welfare Actions': 'நிலுவையில் உள்ள நல நடவடிக்கைகள்',
    'Average Wellness Score': 'சராசரி நல்வாழ்வு மதிப்பீடு',
    'All Personnel': 'அனைத்து வீரர்கள்',
    'Critical Risk': 'தீவிர இடர்',
    'High Risk': 'அதிக இடர்',
    'Moderate Risk': 'மிதமான இடர்',
    'Nominal Risk': 'இயல்பான இடர்',
    'Emotional Stability Index': 'மனநிலை நிலைத்தன்மை குறியீடு',
    'Command Intelligence': 'கட்டளை புலனாய்வு',
    'Behavioral Change Detection': 'நடத்தை மாற்றம் கண்டறிதல்',
    'Stable': 'நிலையான',
    'Historical': 'வரலாற்று',
    'Current': 'தற்போதைய',
    'Rebalance Rosters': 'பட்டியலை மறுசீரமை',
    'Unit Readiness Comparison': 'அலகு தயார்நிலை ஒப்பீடு',
    'View All →': 'அனைத்தும் காண்க →',
    'Force Health Radar': 'படை சுகாதார ரேடார்',
    'High Priority Units': 'உயர் முன்னுரிமை அலகுகள்',
    'AI Early Warnings': 'AI முன்னெச்சரிக்கைகள்',
    'AI Command Recommendations': 'AI கட்டளை பரிந்துரைகள்',
    'Welfare Intervention Progress': 'நலன்புரி தலையீட்டு முன்னேற்றம்',
    'Resource Availability': 'வளங்கள் கிடைக்கின்றன',
    'Mission Impact Metrics': 'பணி தாக்க அளவீடுகள்',
    'AI Executive Insight': 'AI நிர்வாக நுண்ணறிவு',
    'Privacy & Security': 'தனியுரிமை & பாதுகாப்பு',
    'Execute': 'செயல்படுத்து',
    'Close': 'மூடு',
    'Available': 'கிடைக்கும்',
    'Syncing...': 'ஒத்திசைக்கிறது...',
    'Total Active Workforce': 'மொத்த செயல்பாட்டு பணியாளர்கள்',
    'Sync HRMS': 'HRMS ஒத்திசை',
    'Generate Report': 'அறிக்கை உருவாக்கு',
    'PENDING': 'நிலுவையில்',
    'Welcome,': 'வரவேற்கிறோம்,',
    'HRMS Cryptographic Audit Trail': 'HRMS கிரிப்டோகிராஃபிக் தணிக்கை',
    'Platform Infrastructure': 'தளம் உள்கட்டமைப்பு',
    'API Gateway': 'API நுழைவாயில்',
    'Online': 'ஆன்லைன்',
    'Connected': 'இணைக்கப்பட்டது',
    'Active': 'செயல்பாட்டில்',
  },
  te: {
    'PRIMARY MODULES': 'ప్రధాన విభాగాలు',
    'Command Modules': 'కమాండ్ విభాగాలు',
    'Primary Modules': 'ప్రధాన విభాగాలు',
    'ROLE DISPATCH': 'పాత్ర ఎంపిక',
    'Role Dispatch': 'పాత్ర ఎంపిక',
    'Change Profile': 'ప్రొఫైల్ మార్చు',
    'Switch': 'మార్చు',
    'Defense Grade RBAC': 'రక్షణ స్థాయి ప్రవేశ నియంత్రణ',
    'Gateway Active': 'గేట్‌వే క్రియాశీలం',
    'Chief Welfare Officer': 'ప్రధాన సంక్షేమ అధికారి',
    'Dashboard': 'డాష్‌బోర్డ్',
    'Unit Hierarchy': 'యూనిట్ శ్రేణి క్రమం',
    'Personnel Overview': 'సిబ్బంది సమీక్ష',
    'Risk Analysis': 'ప్రమాద విశ్లేషణ',
    'AI Predictions': 'ఏఐ అంచనాలు',
    'Welfare Actions': 'సంక్షేమ చర్యలు',
    'Reports & Analytics': 'నివేదికలు & విశ్లేషణ',
    'Resource Center': 'వనరుల కేంద్రం',
    'Settings': 'సెట్టింగ్‌లు',
    'AI Welfare Intelligence Center': 'ఏఐ సంక్షేమ ఇంటెలిజెన్స్ కేంద్రం',
    'Operational Readiness': 'కార్యాచరణ సంసిద్ధత',
    'Personnel Requiring Support': 'మద్దతు అవసరమైన సైనికులు',
    'Pending Welfare Actions': 'పెండింగ్‌లో ఉన్న సంక్షేమ చర్యలు',
    'Average Wellness Score': 'సగటు ఆరోగ్య స్కోరు',
    'All Personnel': 'అందరు సైనికులు',
    'Critical Risk': 'తీవ్ర ప్రమాదం',
    'High Risk': 'అధిక ప్రమాదం',
    'Moderate Risk': 'మధ్యస్థ ప్రమాదం',
    'Nominal Risk': 'సాధారణ ప్రమాదం',
    'Emotional Stability Index': 'భావోద్వేగ స్థిరత సూచిక',
    'Command Intelligence': 'కమాండ్ ఇంటెలిజెన్స్',
    'Behavioral Change Detection': 'ప్రవర్తనా మార్పు గుర్తింపు',
    'Stable': 'స్థిరంగా',
    'Historical': 'చారిత్రక',
    'Current': 'ప్రస్తుత',
    'Rebalance Rosters': 'రోస్టర్లను పునః సమతుల్యం చేయండి',
    'Unit Readiness Comparison': 'యూనిట్ సంసిద్ధత పోలిక',
    'View All →': 'అన్నీ చూడండి →',
    'High Priority Units': 'అత్యవసర ప్రాధాన్య యూనిట్లు',
    'AI Early Warnings': 'AI ముందస్తు హెచ్చరికలు',
    'AI Command Recommendations': 'AI కమాండ్ సిఫార్సులు',
    'Welfare Intervention Progress': 'సంక్షేమ జోక్యం పురోగతి',
    'Resource Availability': 'వనరుల లభ్యత',
    'Mission Impact Metrics': 'మిషన్ ప్రభావ మెట్రిక్స్',
    'AI Executive Insight': 'AI కార్యనిర్వాహక అంతర్దృష్టి',
    'Execute': 'అమలు చేయండి',
    'Close': 'మూయండి',
    'Available': 'అందుబాటులో ఉంది',
    'Syncing...': 'సమకాలీకరిస్తోంది...',
    'Sync HRMS': 'HRMS సమకాలీకరించు',
    'Generate Report': 'నివేదిక రూపొందించండి',
    'PENDING': 'పెండింగ్',
    'Welcome,': 'స్వాగతం,',
    'Platform Infrastructure': 'ప్లాట్‌ఫారమ్ మౌలిక సదుపాయాలు',
    'Online': 'ఆన్‌లైన్',
    'Connected': 'అనుసంధానించబడింది',
    'Active': 'సక్రియం',
  },
  mr: {
    'PRIMARY MODULES': 'मुख्य मॉड्यूल्स',
    'Command Modules': 'कमांड मॉड्यूल्स',
    'Primary Modules': 'मुख्य मॉड्यूल्स',
    'ROLE DISPATCH': 'भूमिका वाटप',
    'Role Dispatch': 'भूमिका वाटप',
    'Change Profile': 'प्रोफाइल बदला',
    'Switch': 'बदला',
    'Defense Grade RBAC': 'संरक्षण दर्जा सुरक्षा',
    'Gateway Active': 'गेटवे सक्रिय',
    'Chief Welfare Officer': 'मुख्य कल्याण अधिकारी',
    'Dashboard': 'डॅशबोर्ड',
    'Unit Hierarchy': 'सैन्य श्रेणी रचना',
    'Personnel Overview': 'कर्मचारी आढावा',
    'Risk Analysis': 'धोका विश्लेषण',
    'AI Predictions': 'एआय अंदाज',
    'Welfare Actions': 'कल्याणकारी कृती',
    'Reports & Analytics': 'अहवाल आणि विश्लेषण',
    'Resource Center': 'संसाधन केंद्र',
    'Settings': 'सेटिंग्ज',
    'AI Welfare Intelligence Center': 'एआय कल्याण बुद्धिमत्ता केंद्र',
    'Operational Readiness': 'कार्यात्मक सज्जता',
    'Personnel Requiring Support': 'मदतीची गरज असलेले जवान',
    'Pending Welfare Actions': 'प्रलंबित कल्याणकारी कृती',
    'Average Wellness Score': 'सरासरी आरोग्य गुण',
    'All Personnel': 'सर्व कर्मचारी',
    'Critical Risk': 'अतिगंभीर धोका',
    'High Risk': 'उच्च धोका',
    'Moderate Risk': 'मध्यम धोका',
    'Nominal Risk': 'सामान्य धोका',
    'Emotional Stability Index': 'भावनिक स्थिरता निर्देशांक',
    'Command Intelligence': 'कमांड गुप्तचर',
    'Behavioral Change Detection': 'वर्तणूक बदल शोध',
    'Stable': 'स्थिर',
    'Historical': 'ऐतिहासिक',
    'Current': 'सध्याचे',
    'Rebalance Rosters': 'रोस्टर पुनर्संतुलित करा',
    'Unit Readiness Comparison': 'युनिट तयारी तुलना',
    'View All →': 'सर्व पहा →',
    'High Priority Units': 'उच्च प्राधान्य युनिट',
    'AI Early Warnings': 'एआय प्रारंभिक इशारे',
    'AI Command Recommendations': 'एआय कमांड शिफारसी',
    'Welfare Intervention Progress': 'कल्याण हस्तक्षेप प्रगती',
    'Resource Availability': 'संसाधन उपलब्धता',
    'Mission Impact Metrics': 'मिशन प्रभाव निर्देशांक',
    'AI Executive Insight': 'एआय कार्यकारी अंतर्दृष्टी',
    'Execute': 'अंमलात आणा',
    'Close': 'बंद करा',
    'Available': 'उपलब्ध',
    'Syncing...': 'समक्रमित होत आहे...',
    'Total Active Workforce': 'एकूण सक्रिय कार्यबल',
    'Sync HRMS': 'एचआरएमएस सिंक करा',
    'Generate Report': 'अहवाल तयार करा',
    'PENDING': 'प्रलंबित',
    'Welcome,': 'स्वागत आहे,',
    'Platform Infrastructure': 'प्लॅटफॉर्म पायाभूत सुविधा',
    'Online': 'ऑनलाइन',
    'Connected': 'जोडलेले',
    'Active': 'सक्रिय',
  },
  gu: {
    'PRIMARY MODULES': 'મુખ્ય મોડ્યુલ્સ',
    'Command Modules': 'કમાન્ડ મોડ્યુલ્સ',
    'Primary Modules': 'મુખ્ય મોડ્યુલ્સ',
    'ROLE DISPATCH': 'ભૂમિકા વિતરણ',
    'Role Dispatch': 'ભૂમિકા વિતરણ',
    'Change Profile': 'પ્રોફાઇલ બદલો',
    'Switch': 'બદલો',
    'Defense Grade RBAC': 'સંરક્ષણ કક્ષા સુરક્ષા',
    'Gateway Active': 'ગેટવે સક્રિય',
    'Chief Welfare Officer': 'મુખ્ય કલ્યાણ અધિકારી',
    'Dashboard': 'ડેશબોર્ڈ',
    'Unit Hierarchy': 'એકમ વંશવેલો',
    'Personnel Overview': 'કર્મચારી ઝાંખી',
    'Risk Analysis': 'જોખમ વિશ્લેષણ',
    'AI Predictions': 'એઆઈ આગાહીઓ',
    'Welfare Actions': 'કલ્યાણકારી પગલાં',
    'Reports & Analytics': 'અહેવાલો અને વિશ્લેષણ',
    'Resource Center': 'સંસાધન કેન્દ્ર',
    'Settings': 'સેટિંગ્સ',
    'AI Welfare Intelligence Center': 'એઆઈ કલ્યાણ ગુપ્તચર કેન્દ્ર',
    'Operational Readiness': 'કાર્યકારી સજ્જતા',
    'Personnel Requiring Support': 'સહાયની જરૂરિયાતવાળા જવાનો',
    'Pending Welfare Actions': 'બાકી કલ્યાણકારી કાર્યો',
    'Average Wellness Score': 'સરેરાશ સુખાકારી સ્કોર',
    'All Personnel': 'બધા કર્મચારીઓ',
    'Critical Risk': 'ગંભીર જોખમ',
    'High Risk': 'ઉચ્ચ જોખમ',
    'Moderate Risk': 'મધ્યમ જોખમ',
    'Nominal Risk': 'સામાન્ય જોખમ',
    'Emotional Stability Index': 'ભાવનાત્મક સ્થિરતા સૂચકાંક',
    'Command Intelligence': 'કમાન્ડ ગુપ્ત માહિતી',
    'Behavioral Change Detection': 'વ્યવહારિક ફેરફાર શોધ',
    'Stable': 'સ્થિર',
    'Historical': 'ઐતિહાસિક',
    'Current': 'વર્તમાન',
    'Rebalance Rosters': 'રોસ્ટર પુન:સંતુલિત કરો',
    'Unit Readiness Comparison': 'એકમ તત્પરતા સરખામણી',
    'View All →': 'બધું જુઓ →',
    'High Priority Units': 'ઉચ્ચ પ્રાથમિકતા એકમો',
    'AI Early Warnings': 'AI પ્રારંભિક ચેતવણી',
    'AI Command Recommendations': 'AI કમાન્ડ ભલામણો',
    'Welfare Intervention Progress': 'કલ્યાણ હસ્તક્ષેપ પ્રગતિ',
    'Resource Availability': 'સ્ત્રોત ઉપલબ્ધતા',
    'Mission Impact Metrics': 'મિશન અસર માપદંડ',
    'Execute': 'અમલ કરો',
    'Close': 'બંધ કરો',
    'Available': 'ઉપલબ્ધ',
    'Syncing...': 'સિંક થઈ રહ્યું છે...',
    'Sync HRMS': 'HRMS સિંક કરો',
    'Generate Report': 'અહેવાલ બનાવો',
    'PENDING': 'બાકી',
    'Welcome,': 'આવો,',
    'Online': 'ઓનલાઈન',
    'Connected': 'જોડાયેલ',
    'Active': 'સક્રિય',
  },
  kn: {
    'PRIMARY MODULES': 'ಮುಖ್ಯ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    'Command Modules': 'ಕಮಾಂಡ್ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    'Primary Modules': 'ಮುಖ್ಯ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    'ROLE DISPATCH': 'ಪಾತ್ರ ನಿಯೋಜನೆ',
    'Role Dispatch': 'ಪಾತ್ರ ನಿಯೋಜನೆ',
    'Change Profile': 'ಪ್ರೊಫೈಲ್ ಬದಲಾಯಿಸಿ',
    'Switch': 'ಬದಲಾಯಿಸಿ',
    'Defense Grade RBAC': 'ರಕ್ಷಣಾ ದರ್ಜೆಯ ಪ್ರವೇಶ',
    'Gateway Active': 'ಗೇಟ್‌ವೇ ಸಕ್ರಿಯ',
    'Chief Welfare Officer': 'ಮುಖ್ಯ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿ',
    'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'Unit Hierarchy': 'ಘಟಕ ಕ್ರಮಾನುಗತ',
    'Personnel Overview': 'ಸಿಬ್ಬಂದಿ ಅವಲೋಕನ',
    'Risk Analysis': 'ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ',
    'AI Predictions': 'ಎಐ ಮುನ್ಸೂಚನೆಗಳು',
    'Welfare Actions': 'ಕ್ಷೇಮಾಭಿವೃದ್ಧಿ ಕ್ರಮಗಳು',
    'Reports & Analytics': 'ವರದಿಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆ',
    'Resource Center': 'ಸಂಪನ್ಮೂಲ ಕೇಂದ್ರ',
    'Settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'AI Welfare Intelligence Center': 'ಎಐ ಕಲ್ಯಾಣ ಗುಪ್ತಚರ ಕೇಂದ್ರ',
    'Operational Readiness': 'ಕಾರ್ಯಾಚರಣೆಯ ಸನ್ನದ್ಧತೆ',
    'Personnel Requiring Support': 'ಬೆಂಬಲ ಅಗತ್ಯವಿರುವ ಸಿಬ್ಬಂದಿ',
    'Pending Welfare Actions': 'ಬಾಕಿ ಇರುವ ಕಲ್ಯಾಣ ಕ್ರಮಗಳು',
    'Average Wellness Score': 'ಸರಾಸರಿ ಕ್ಷೇಮ ಸ್ಕೋರ್',
    'All Personnel': 'ಎಲ್ಲಾ ಸಿಬ್ಬಂದಿ',
    'Critical Risk': 'ತೀವ್ರ ಅಪಾಯ',
    'High Risk': 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    'Moderate Risk': 'ಮಧ್ಯಮ ಅಪಾಯ',
    'Nominal Risk': 'ಸಾಮಾನ್ಯ ಅಪಾಯ',
    'Emotional Stability Index': 'ಭಾವನಾತ್ಮಕ ಸ್ಥಿರತಾ ಸೂಚ್ಯಂಕ',
    'Command Intelligence': 'ಕಮಾಂಡ್ ಗುಪ್ತಚರ',
    'Behavioral Change Detection': 'ವರ್ತನಾ ಬದಲಾವಣೆ ಪತ್ತೆ',
    'Stable': 'ಸ್ಥಿರ',
    'Historical': 'ಐತಿಹಾಸಿಕ',
    'Current': 'ಪ್ರಸ್ತುತ',
    'Rebalance Rosters': 'ರೋಸ್ಟರ್ ಮರು-ಸಮತೋಲಿಸಿ',
    'Unit Readiness Comparison': 'ಘಟಕ ಸಿದ್ಧತೆ ತುಲನೆ',
    'View All →': 'ಎಲ್ಲ ನೋಡಿ →',
    'High Priority Units': 'ಹೆಚ್ಚಿನ ಆದ್ಯತೆ ಘಟಕಗಳು',
    'AI Early Warnings': 'AI ಮುಂಚಿನ ಎಚ್ಚರಿಕೆಗಳು',
    'AI Command Recommendations': 'AI ಕಮಾಂಡ್ ಶಿಫಾರಸುಗಳು',
    'Welfare Intervention Progress': 'ಕಲ್ಯಾಣ ಹಸ್ತಕ್ಷೇಪ ಪ್ರಗತಿ',
    'Resource Availability': 'ಸಂಪನ್ಮೂಲ ಲಭ್ಯತೆ',
    'Mission Impact Metrics': 'ಮಿಷನ್ ಪ್ರಭಾವ ಮಾಪಕಗಳು',
    'Execute': 'ಕಾರ್ಯಗತ ಮಾಡಿ',
    'Close': 'ಮುಚ್ಚಿ',
    'Available': 'ಲಭ್ಯ',
    'Syncing...': 'ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...',
    'Sync HRMS': 'HRMS ಸಿಂಕ್ ಮಾಡಿ',
    'Generate Report': 'ವರದಿ ರಚಿಸಿ',
    'PENDING': 'ಬಾಕಿ',
    'Welcome,': 'ಸ್ವಾಗತ,',
    'Online': 'ಆನ್‌ಲೈನ್',
    'Connected': 'ಸಂಪರ್ಕಿತ',
    'Active': 'ಸಕ್ರಿಯ',
  },
  ml: {
    'PRIMARY MODULES': 'പ്രധാന മൊഡ്യൂളുകൾ',
    'Command Modules': 'കമാൻഡ് മൊഡ്യൂളുകൾ',
    'Primary Modules': 'പ്രധാന മൊഡ്യൂളുകൾ',
    'ROLE DISPATCH': 'റോൾ തെരഞ്ഞെടുപ്പ്',
    'Role Dispatch': 'റോൾ തെരഞ്ഞെടുപ്പ്',
    'Change Profile': 'പ്രൊഫൈൽ മാറ്റുക',
    'Switch': 'മാറ്റുക',
    'Defense Grade RBAC': 'പ്രതിരോധ ഗ്രേഡ് സുരക്ഷ',
    'Gateway Active': 'ഗേറ്റ്‌വേ സജീവം',
    'Chief Welfare Officer': 'ചീഫ് വെൽഫെയർ ഓഫീസർ',
    'Dashboard': 'ഡാഷ്‌ബോർഡ്',
    'Unit Hierarchy': 'യൂണിറ്റ് ശ്രേണി ഘടന',
    'Personnel Overview': 'ജീവനക്കാരുടെ വിവരണം',
    'Risk Analysis': 'അപകടസാധ്യത വിശകലനം',
    'AI Predictions': 'എഐ പ്രവചനങ്ങൾ',
    'Welfare Actions': 'ക്ഷേമ പ്രവർത്തനങ്ങൾ',
    'Reports & Analytics': 'റിപ്പോർട്ടുകളും വിശകലനവും',
    'Resource Center': 'വിഭവ കേന്ദ്രം',
    'Settings': 'ക്രമീകരണങ്ങൾ',
    'AI Welfare Intelligence Center': 'എഐ വെൽഫെയർ ഇന്റലിജൻസ് സെന്റർ',
    'Operational Readiness': 'പ്രവർത്തന സജ്ജത',
    'Personnel Requiring Support': 'പിന്തുണ ആവശ്യമുള്ള സൈനികർ',
    'Pending Welfare Actions': 'തീർപ്പാക്കാത്ത ക്ഷേമ നടപടികൾ',
    'Average Wellness Score': 'ശരാശരി ക്ഷേമ സ്കോർ',
    'All Personnel': 'എല്ലാ ജീവനക്കാരും',
    'Critical Risk': 'ഗുരുതരമായ അപകടം',
    'High Risk': 'ഉയർന്ന അപകടസാധ്യത',
    'Moderate Risk': 'മിതമായ അപകടസാധ്യത',
    'Nominal Risk': 'സാധാരണ നില',
    'Emotional Stability Index': 'വൈകാരിക സ്ഥിരത സൂചിക',
    'Command Intelligence': 'കമാൻഡ് ഇന്റലിജൻസ്',
    'Behavioral Change Detection': 'പെരുമാറ്റ മാറ്റ കണ്ടെത്തൽ',
    'Stable': 'സ്ഥിരമായ',
    'Historical': 'ചരിത്രപരമായ',
    'Current': 'നിലവിലുള്ള',
    'Rebalance Rosters': 'റോസ്റ്ററുകൾ പുനഃക്രമീകരിക്കുക',
    'Unit Readiness Comparison': 'യൂണിറ്റ് സജ്ജത താരതമ്യം',
    'View All →': 'എല്ലാം കാണുക →',
    'High Priority Units': 'ഉയർന്ന മുൻഗണനാ യൂണിറ്റുകൾ',
    'AI Early Warnings': 'AI മുൻ‌കൂർ മുന്നറിയിപ്പുകൾ',
    'AI Command Recommendations': 'AI കമാൻഡ് ശുപാർശകൾ',
    'Welfare Intervention Progress': 'ക്ഷേമ ഇടപെടൽ പുരോഗതി',
    'Resource Availability': 'വിഭവ ലഭ്യത',
    'Mission Impact Metrics': 'മിഷൻ ആഘാത അളവുകൾ',
    'Execute': 'നടപ്പാക്കുക',
    'Close': 'അടക്കുക',
    'Available': 'ലഭ്യമാണ്',
    'Syncing...': 'സമന്വയിക്കുന്നു...',
    'Sync HRMS': 'HRMS സമന്വയിപ്പിക്കുക',
    'Generate Report': 'റിപ്പോർട്ട് ഉണ്ടാക്കുക',
    'PENDING': 'തീർ‌പ്പാക്കിയിട്ടില്ല',
    'Welcome,': 'സ്വാഗതം,',
    'Online': 'ഓൺലൈൻ',
    'Connected': 'ബന്ധിപ്പിച്ചു',
    'Active': 'സജീവം',
  },
  or: {
    'PRIMARY MODULES': 'ପ୍ରମୁଖ ମଡ୍ୟୁଲଗୁଡ଼ିକ',
    'Command Modules': 'କମାଣ୍ଡ ମଡ୍ୟୁଲଗୁଡ଼ିକ',
    'Primary Modules': 'ପ୍ରମୁଖ ମଡ୍ୟୁଲଗୁଡ଼ିକ',
    'ROLE DISPATCH': 'ଭୂମିକା ଚୟନ',
    'Role Dispatch': 'ଭୂମିକା ଚୟନ',
    'Change Profile': 'ପ୍ରୋଫାଇଲ୍ ବଦଳାନ୍ତୁ',
    'Switch': 'ବଦଳାନ୍ତୁ',
    'Defense Grade RBAC': 'ପ୍ରତିରକ୍ଷା ଗ୍ରେଡ୍ ସୁରକ୍ଷା',
    'Gateway Active': 'ଗେଟୱେ ସକ୍ରିୟ',
    'Chief Welfare Officer': 'ମୁଖ୍ୟ କଲ୍ୟାଣ ଅଧିକାରୀ',
    'Dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'Unit Hierarchy': 'ୟୁନିଟ୍ ଶୃଙ୍ଖଳା',
    'Personnel Overview': 'କର୍ମଚାରୀ ସମୀକ୍ଷା',
    'Risk Analysis': 'ବିପଦ ବିଶ୍ଳେଷଣ',
    'AI Predictions': 'ଏଆଇ ଭବିଷ୍ୟବାଣୀ',
    'Welfare Actions': 'କଲ୍ୟାଣମୂଳକ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    'Reports & Analytics': 'ରିପୋର୍ଟ ଏବଂ ବିଶ୍ଳେଷଣ',
    'Resource Center': 'ସମ୍ବଳ କେନ୍ଦ୍ର',
    'Settings': 'ସେଟିଙ୍ଗ୍ସ',
    'AI Welfare Intelligence Center': 'ଏଆଇ କଲ୍ୟାଣ ଗୁଇନ୍ଦା କେନ୍ଦ୍ର',
    'Operational Readiness': 'କାର୍ଯ୍ୟକ୍ଷମ ପ୍ରସ୍ତୁତି',
    'Personnel Requiring Support': 'ସହାୟତା ଆବଶ୍ୟକ କରୁଥିବା କର୍ମଚାରୀ',
    'Pending Welfare Actions': 'ବକେୟା କଲ୍ୟାଣ କାର୍ଯ୍ୟ',
    'Average Wellness Score': 'ହାରାହାରି ସୁସ୍ଥତା ସ୍କୋର',
    'All Personnel': 'ସମସ୍ତ କର୍ମଚାରୀ',
    'Critical Risk': 'ଗୁରୁତର ବିପଦ',
    'High Risk': 'ଉଚ୍ଚ ବିପଦ',
    'Moderate Risk': 'ମଧ୍ୟମ ବିପଦ',
    'Nominal Risk': 'ସ୍ୱାଭାବିକ ବିପଦ',
    'Emotional Stability Index': 'ଭାବନାତ୍ମକ ସ୍ଥିରତା ସୂଚକ',
    'Command Intelligence': 'କମାଣ୍ଡ ଗୋଇନ୍ଦା',
    'Behavioral Change Detection': 'ଆଚରଣ ପରିବର୍ତ୍ତନ ଚିହ୍ନଟ',
    'Stable': 'ସ୍ଥିର',
    'Historical': 'ଐତିହାସିକ',
    'Current': 'ବର୍ତ୍ତମାନ',
    'Rebalance Rosters': 'ରୋଷ୍ଟର ପୁନଃ ସଂତୁଳିତ କରନ୍ତୁ',
    'Unit Readiness Comparison': 'ୟୁନିଟ ପ୍ରସ୍ତୁତି ତୁଳନା',
    'View All →': 'ସବୁ ଦେଖନ୍ତୁ →',
    'High Priority Units': 'ଉଚ୍ଚ ଅଗ୍ରାଧିକାର ୟୁନିଟ',
    'AI Early Warnings': 'AI ପ୍ରାରମ୍ଭିକ ସତର୍କତା',
    'AI Command Recommendations': 'AI କମାଣ୍ଡ ସୁପାରିଶ',
    'Welfare Intervention Progress': 'କଲ୍ୟାଣ ହସ୍ତକ୍ଷେପ ଅଗ୍ରଗତି',
    'Resource Availability': 'ସମ୍ବଳ ଉପଲବ୍ଧତା',
    'Mission Impact Metrics': 'ମିଶନ ପ୍ରଭାବ ମାପକ',
    'Execute': 'କାର୍ଯ୍ୟକର',
    'Close': 'ବନ୍ଦ କରନ୍ତୁ',
    'Available': 'ଉପଲବ୍ଧ',
    'Syncing...': 'ସିଙ୍କ ହେଉଛି...',
    'Sync HRMS': 'HRMS ସିଙ୍କ କରନ୍ତୁ',
    'Generate Report': 'ରିପୋର୍ଟ ତିଆରି କରନ୍ତୁ',
    'PENDING': 'ବାକି',
    'Welcome,': 'ସ୍ୱାଗତ,',
    'Online': 'ଅନ୍‌ଲାଇନ',
    'Connected': 'ସଂଯୁକ୍ତ',
    'Active': 'ସକ୍ରିୟ',
  },
};

interface LanguageStore {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
}

export const useLanguageStore = create<LanguageStore>((set, get) => {
  const savedLang = (localStorage.getItem('pswms_language') as LanguageCode) || 'en';

  return {
    currentLanguage: savedLang in TRANSLATIONS ? savedLang : 'en',
    setLanguage: (lang: LanguageCode) => {
      localStorage.setItem('pswms_language', lang);
      set({ currentLanguage: lang });
    },
    t: (key: string, fallback?: string): string => {
      if (!key) return fallback || '';
      const current = get().currentLanguage;
      if (current === 'en') {
        return fallback || key;
      }

      // 1. Direct check in TRANSLATIONS dictionary
      const dict = TRANSLATIONS[current];
      if (dict && dict[key]) {
        return dict[key];
      }

      // 2. Direct check in COMMON_PHRASE_TRANSLATIONS dictionary
      const phrases = COMMON_PHRASE_TRANSLATIONS[current];
      if (phrases && phrases[key]) {
        return phrases[key];
      }

      // 3. Trimmed check
      const trimmedKey = key.trim();
      if (phrases && phrases[trimmedKey]) {
        return phrases[trimmedKey];
      }

      // 4. Fallback to English translation
      const enDict = TRANSLATIONS['en'];
      if (enDict && enDict[key]) {
        return enDict[key];
      }

      return fallback || key;
    },
  };
});
